### ISSUE TITLE
Spatial problem

### ISSUE THREAD

**Issue by fithisux** [neo4j-contrib/spatial#103]
Hi I have neo4j 1.9.1 with plugin installed on ubuntu 13.04 x64.

On the client side I add nodes with lat/lon properties equal to 5.

When I do a within_distance query around (5,5) with radius 10 I get nothing

snippets

if(!index.existsForNodes("layer1"))
        {
            spatialindex = index.forNodes("layer1",SpatialIndexProvider.SIMPLE_POINT_CONFIG);            

```
    }
    else
    {
        spatialindex=index.forNodes("layer1");
    }
```

Node v = this.bgr.gds.createNode();
v.setProperty("lat", pkg.latitude);
        v.setProperty("lon", pkg.longitude);
        this.spatialindex.add(v,"dummy","value"); 

public Iterator<Node> queryPackagesSpatial(BiopolisSpatialQuery sq)
    {
        HashMap<String, Object> params = new HashMap<String, Object>();
        params.put(LayerNodeIndex.POINT_PARAMETER, new Double[]{sq.longitude,sq.latitude} );
        params.put(LayerNodeIndex.DISTANCE_IN_KM_PARAMETER, sq.radius);
        return this.bgr.pkg_mgmnt.spatialindex.query(LayerNodeIndex.WITHIN_DISTANCE_QUERY,params);
    }

**Comment by ehx-v1** [comment]
I'd suppose distance 0 doesn't count for some reason, somehow it looks like that's done on purpose for some complicated logic

**Comment by craigtaverner** [comment]
The old IndexProvider API was removed in 3.0.
