### ISSUE TITLE
REST API: deleting of spatial index causes endless loop

### ISSUE THREAD

**Issue by Lin-Daiyu** [neo4j-contrib/spatial#109]
When I want to clear a database that contains the characteristical subgraph of the spatial index it ends in an endless loop of deleting and recreating this subgraph which can be stopped just be turning off the server. 

```
START n=node(*)
MATCH n-[r?]->()
DELETE r
WHERE ID(n) <> 0
DELETE n
```

Also I don't have a clue, how I could delete just one layer. Is there a way? What happens to the spatial nodes of the deleted layer?

**Comment by ehx-v1** [comment]
you sure that query should clear the database? I always use `match ()-[r]-() delete r; match (n) delete n`

**Comment by ehx-v1** [comment]
however, if your query does work, clearing a layer should work quite similarly:

```
START n=node(*{layer:"<layer_name>"})
MATCH (:ReferenceNode)-[r1:LAYER]->n-[r2*]->(n2)
DELETE r1
DELETE r2
WHERE ID(n2) <> 0
DELETE n2
WHERE ID(n) <> 0
DELETE n
```
this would clean up the whole RTree (as long as it would do anything at all) including the metadata, and the incoming LAYER relationship

**Comment by craigtaverner** [comment]
REST API is deprecated. See the new procedures instead.
