### ISSUE TITLE
REST API: no functions to handle searches with shapes

### ISSUE THREAD

**Issue by Lin-Daiyu** [neo4j-contrib/spatial#110]
The functions findGeometriesInBBox and findGeometriesWithinDistance just handle points. But if I want to search for intersections between shapes (circles, polygons) in e.g. a bounding box, there are no functions to do this.

**Comment by ehx-v1** [comment]
I thought they handle WKT of any kind, that's what it also appeared like to me
however, you should know that the geometries must be COMPLETELY within your search frame (BBox or distance), or they don't count
#217 is stating this problem

**Comment by craigtaverner** [comment]
REST API is deprecated
