### ISSUE TITLE
REST API: cypher doesn't retrieve results

### ISSUE THREAD

**Issue by Lin-Daiyu** [neo4j-contrib/spatial#111]
When I try to query the spatial nodes via Cypher nothing is retrieved.

START n=node:geom('withinDistance:[13.73, 13.75, 51.048, 51.05, 5.0]') 
RETURN n

**Comment by ehx-v1** [comment]
perhaps there are truly no nodes within the distance you specified?

**Comment by ehx-v1** [comment]
also, perhaps you should have another look at your parameters? in any example I found there are only three for withinDistance, and you put five

**Comment by craigtaverner** [comment]
REST API is deprecated
