### ISSUE TITLE
Intersects on array of points is very slow

### ISSUE THREAD

**Issue by craigtaverner** [neo4j-contrib/spatial#112]
Albert Leung reported that his test code which tried to find Geometries that intersect any of a large set of points was running incredibly slow, when compared with what he felt was an equivalent search on SQL Server. When asked to describe the case in more detail, Albert said:

"It’s basically a reverse geo-code of all the points in the trip. The trip can cover about 30 miles on multiple roads. The shape is ad hoc and definitely cannot fit conveniently into a single bounding box. We need to associate each location to a particular road getting the road type and feature classification from the U.S. Census data but to make this query fast we need to make a single query that returns all the information we need for each location. From my reading of this email, neo4j-spatial is not optimized for this type of problem."

My feeling is that this is something Neo4j can do fast, but only of we pass the entire set of points as a single Geometry into the RTree search instead of iterating over the set and performing individual searches as Albert did. We can pass the points in as a MultiPoint, or as a LineString. Since the original use case was for a drive 'trip', I would think a LineString makes more sense for this case. We should write a test case that demonstrates the difference in performance between three approaches:
- Iterating over set of points
- build a MultiPoint and search with that
- build a LineString and search with that

We would expect the LineString and MultiPoint to perform very much better than the set interation, especially if the sample Geometry sets (roads) is very large, and the set of test points quite large. Albert used a 30mile drive, and may have been testing against a city or even state size roads database. We could create something similar and report the findings.

**Comment by ehx-v1** [comment]
as a solution to the actual problem, I would suggest trying to make the code notice that multiple points are searched shortly one after another, and when this pattern is found cache the search data and pack it into a MultiPoint (which would be the more general Geometry), does that sound like a possible approach?

**Comment by craigtaverner** [comment]
The ability to search against complex geometries has always been there, and the Java API assumes you can build these using JTS before calling the geoprocessing framework. For the procedures, there is a lot of related work necessary to help build complex geometries, but that is out of scope for this library.
