### ISSUE TITLE
Fix OSM import

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/spatial#118]

**Comment by ehx-v1** [comment]
but existing functionality will remain I hope? because when performance is not the only thing of matter (e.g. if you're still at getting it to run) the BatchInserter quite sucks with its (relatively) unverbose exceptions (compared to a graph database)

**Comment by craigtaverner** [comment]
We never got round to trying the new importer. But I think the normal non-batch importer should remain indefinitely. It is only the batch version we would want to replace with the new approach.

**Comment by ehx-v1** [comment]
btw my FileImporter now has 2 different implementations of OSM import, it first tries importing with the BatchInserter version, and if that throws an exception it retries with a GraphDatabaseService, if that works it prints the BatchInserter error as warning, if the graph database import throws an exception too the BatchInserter exception is attached as suppressed

**Comment by craigtaverner** [comment]
Last year we wrote a new OSM importer as a separate project. See https://github.com/neo4j-contrib/osm

While there are things that can still be done, like make use of that importer in this library (currently the two are very separate, although they build a very similar, almost identical OSM model), I think that library is enough to close this issue.
