### ISSUE TITLE
Neo4j in geoserver doesn't read correctly the test data neostore.id

### ISSUE THREAD

**Issue by reyman** [neo4j-contrib/spatial#12]
I'm using this configuration 
- Geoserver V 2.1.1 
- Geotools 2.7.2 (rev 37473)

With plugin neo4j .war into tomcat6 and lib into WEB-INF : 

activation-1.1.jar
aopalliance-1.0.jar
avalon-framework-api-4.3.1.jar
avalon-framework-impl-4.3.1.jar
batik-anim-1.7.jar
batik-awt-util-1.7.jar
batik-bridge-1.7.jar
batik-css-1.7.jar
batik-dom-1.7.jar
batik-ext-1.7.jar
batik-gvt-1.7.jar
batik-parser-1.7.jar
batik-script-1.7.jar
batik-svg-dom-1.7.jar
batik-svggen-1.7.jar
batik-transcoder-1.7.jar
batik-util-1.7.jar
batik-xml-1.7.jar
bcmail-jdk14-138.jar
bcprov-jdk14-138.jar
cglib-nodep-2.1_3.jar
common-2.6.0.jar
commons-beanutils-1.7.0.jar
commons-codec-1.2.jar
commons-collections-3.1.jar
commons-dbcp-1.3.jar
commons-digester-1.7.jar
commons-fileupload-1.2.1.jar
commons-httpclient-3.1.jar
commons-io-1.3.2.jar
commons-jxpath-1.3.jar
commons-lang-2.1.jar
commons-logging-1.1.1.jar
commons-pool-1.5.3.jar
commons-validator-1.1.4.jar
com.noelios.restlet-1.0.8.jar
com.noelios.restlet.ext.servlet-1.0.8.jar
com.noelios.restlet.ext.simple-1.0.8.jar
ecore-2.6.1.jar
ehcache-1.6.2.jar
ezmorph-1.0.6.jar
fop-0.94.jar
freemarker-2.3.13.jar
geronimo-jta_1.1_spec-1.1.1.jar
gt-api-2.7.2.jar
gt-arcgrid-2.7.2.jar
gt-coverage-2.7.2.jar
gt-cql-2.7.2.jar
gt-data-2.7.2.jar
gt-epsg-hsql-2.7.2.jar
gt-geotiff-2.7.2.jar
gt-graph-2.7.2.jar
gt-gtopo30-2.7.2.jar
gt-image-2.7.2.jar
gt-imageio-ext-gdal-2.7.2.jar
gt-imagemosaic-2.7.2.jar
gt-jdbc-2.7.2.jar
gt-jdbc-postgis-2.7.2.jar
gt-main-2.7.2.jar
gt-metadata-2.7.2.jar
gt-opengis-2.7.2.jar
gt-property-2.7.2.jar
gt-referencing-2.7.2.jar
gt-render-2.7.2.jar
gt-shapefile-2.7.2.jar
gt-shapefile-renderer-2.7.2.jar
gt-svg-2.7.2.jar
gt-temporal-2.7.2.jar
gt-validation-2.7.2.jar
gt-wfs-2.7.2.jar
gt-wms-2.7.2.jar
gt-xml-2.7.2.jar
gt-xsd-core-2.7.2.jar
gt-xsd-fes-2.7.2.jar
gt-xsd-filter-2.7.2.jar
gt-xsd-gml2-2.7.2.jar
gt-xsd-gml3-2.7.2.jar
gt-xsd-ows-2.7.2.jar
gt-xsd-sld-2.7.2.jar
gt-xsd-wcs-2.7.2.jar
gt-xsd-wfs-2.7.2.jar
gwc-2.1.1.jar
gwc-core-1.2.6.jar
gwc-diskquota-1.2.6.jar
gwc-georss-1.2.6.jar
gwc-gmaps-1.2.6.jar
gwc-kml-1.2.6.jar
gwc-rest-1.2.6.jar
gwc-tms-1.2.6.jar
gwc-ve-1.2.6.jar
gwc-wms-1.2.6.jar
gwc-wmts-1.2.6.jar
h2-1.1.119.jar
hsqldb-1.8.0.7.jar
htmlvalidator-1.2.jar
imageio-ext-arcgrid-1.0.8.jar
imageio-ext-customstreams-1.0.8.jar
imageio-ext-gdalarcbinarygrid-1.0.8.jar
imageio-ext-gdal-bindings-1.4.5b.jar
imageio-ext-gdaldted-1.0.8.jar
imageio-ext-gdalecw-1.0.8.jar
imageio-ext-gdalecwjp2-1.0.8.jar
imageio-ext-gdalehdr-1.0.8.jar
imageio-ext-gdalenvihdr-1.0.8.jar
imageio-ext-gdalerdasimg-1.0.8.jar
imageio-ext-gdalframework-1.0.8.jar
imageio-ext-gdalkakadujp2-1.0.8.jar
imageio-ext-gdalmrsid-1.0.8.jar
imageio-ext-gdalmrsidjp2-1.0.8.jar
imageio-ext-gdalnitf-1.0.8.jar
imageio-ext-geocore-1.0.8.jar
imageio-ext-imagereadmt-1.0.8.jar
imageio-ext-tiff-1.0.8.jar
imageio-ext-utilities-1.0.8.jar
itext-2.1.5.jar
jai_codec-1.1.3.jar
jai_core-1.1.3.jar
jai_imageio-1.1.jar
jdom-1.0.jar
je-4.1.7.jar
jettison-1.0.1.jar
json-lib-2.1-jdk13.jar
json-lib-2.2.3-jdk15.jar
json-simple-1.1.jar
jsr-275-1.0-beta-2.jar
jts-1.11.jar
jt-utils-1.1.1.jar
jt-vectorbinarize-1.1.1.jar
junit-4.8.2.jar
log4j-1.2.14.jar
mail-1.4.jar
main-2.1.1.jar
neo4j-kernel-1.4.jar
neo4j-lucene-index-1.4.jar
neo4j-spatial-0.6-SNAPSHOT.jar
net.opengis.ows-2.7.2.jar
net.opengis.wcs-2.7.2.jar
net.opengis.wfs-2.7.2.jar
org.json-2.0.jar
org.restlet-1.0.8.jar
org.restlet.ext.freemarker-1.0.8.jar
org.restlet.ext.json-1.0.8.jar
org.restlet.ext.spring-1.0.8.jar
org.simpleframework-3.1.3.jar
org.w3.xlink-2.7.2.jar
oro-2.0.8.jar
osm-test-data-20100819.jar
ows-2.1.1.jar
ows-2.1.1-tests.jar
picocontainer-1.2.jar
platform-2.1.1.jar
postgresql-8.4-701.jdbc3.jar
rest-2.1.1.jar
restconfig-2.1.1.jar
servlet-api-2.4.jar
shp-test-data-20100819.jar
slf4j-api-1.5.8.jar
slf4j-log4j12-1.4.2.jar
spring-aop-2.5.5.jar
spring-beans-2.5.5.jar
spring-context-2.5.5.jar
spring-context-support-2.5.5.jar
spring-core-2.5.5.jar
spring-jdbc-2.5.5.jar
spring-security-core-2.0.6.RELEASE.jar
spring-security-core-tiger-2.0.6.RELEASE.jar
spring-support-2.0.8.jar
spring-tx-2.5.5.jar
spring-web-2.5.5.jar
spring-webmvc-2.5.5.jar
stax-1.2.0.jar
stax-api-1.0.1.jar
vecmath-1.3.2.jar
wcs1_0-2.1.1.jar
wcs1_1-2.1.1.jar
wcs-2.1.1.jar
web-core-2.1.1.jar
web-demo-2.1.1.jar
web-gwc-2.1.1.jar
web-security-2.1.1.jar
web-wcs-2.1.1.jar
web-wfs-2.1.1.jar
web-wms-2.1.1.jar
wfs-2.1.1.jar
wicket-1.4.12.jar
wicket-extensions-1.4.12.jar
wicket-ioc-1.4.12.jar
wicket-spring-1.4.12.jar
wms-2.1.1.jar
xalan-2.7.0.jar
xercesImpl-2.6.2.jar
xml-apis-1.3.04.jar
xml-apis-ext-1.3.04.jar
xml-apis-xerces-2.7.1.jar
xmlgraphics-commons-1.2.jar
xpp3-1.1.3.4.O.jar
xpp3_min-1.1.4c.jar
xsd-2.6.0.jar
xstream-1.3.1.jar

Neo4 run into geoserver normaly,
After construction of neo4j test with this command : mvn test -Dtest=TestDynamicLayers
I have this osm layer into neo4j db : 1311178267339 (dl here if you want to test http://dl.dropbox.com/u/3026820/1311178267339.tar.gz )

I'm trying to load neostore.id with this parameter into geoserver neo4j store panel "URL connection parameters" : 
file:/home/srey/TRAVAUX/THESE/REPOSITORY_GIT/neo4j-spatial/target/var/neo4j-db/1311178267339/neostore.id

I have this error :
Error creating data store, check the parameters. Error message: Could not acquire data access 'Neo4j-Spatial Test'

So i think this tutorial is outdated : http://wiki.neo4j.org/content/Neo4j_Spatial_in_GeoServer
And i'm really sorry because i can visualize neo4 data with geoserver :-/
Do you have an idea ? How can i resolve this problem ? 
Thanks a lot

**Comment by ehx-v1** [comment]
I think that means it does
