### ISSUE TITLE
REST API missing delete layer and remove node from layer methods

### ISSUE THREAD

**Issue by craigtaverner** [neo4j-contrib/spatial#139]
Two obvious methods missing from the REST API are methods to remove a node from a layer and one for deleting the entire layer.

This work should also consider the fact that layer deleting in the Java API is not thoroughly tested. So work on the Java API is also required.

**Comment by Infiniverse** [comment]
Was there any progress on this issue? I've found myself with a database with a corrupted spatial index, but I can't work out what the obvious way of deleting the index is so that I can start again.

**Comment by versae** [comment]
Any progress?

**Comment by nguyenchiencong** [comment]
:+1:

**Comment by ehx-v1** [comment]
is the Cypher statement combination `match ()-[r]-() delete r; match (n) delete n` a safe way to make tabula rasa, or does the index make some problems about that?

**Comment by craigtaverner** [comment]
The line starting with idlookup.remove cannot succeed because it casts the node to a record which it is not. I suspect this bug was introduced a while back and never fixed. However, this appear to be part of the IndexProvider API which we are removing for 3.0 since we can use procedures to access spatial from cypher, and that will remove a number of issues. We could look for a simple fix for this for the 2.x releases, but for Neo4j 3.0 this code will not even exist.

**Comment by Infiniverse** [comment]
We should fix this bug (which I think I found the root cause of in #236). There are a lot of us using spatial indexes, and moving to 3.0 will be quite a bit of work given it's a complete change of process.

**Comment by ehx-v1** [comment]
The safest fix, I think, would be making a new Node class both inheriting from the database Node implementation and implementing SpatialDatabaseRecord, and making all spatial nodes inherit from this class. However, that would be quite a work i guess...

**Comment by Infiniverse** [comment]
I'm not sure why the change in #236 wouldn't apply.

**Comment by ehx-v1** [comment]
Another fix that appears quite clean to me is calling methods to retrieve the SpatialDatabaseRecord the Node belongs to, and using that record. If these methods already exist (what I would strongly assume), this might even be a one-line fix.

**Comment by ehx-v1** [comment]
Just noticed that such a one-line fix is exactly what @Infiniverse proposed in #236.

**Comment by ehx-v1** [comment]
@Infiniverse why don't you try for a pull request? If you have trouble with how to sign the CLA, @craigtaverner has linked the instructions in a pull request of mine (which was cancelled because it fits better in an older branch, and which I'll look up once I'm at a computer again, Git from the mobile quite sucks).

**Comment by craigtaverner** [comment]
@Infiniverse and @ehx-v1 - the change in #235 looks good, but I would strongly prefer a matching test case, one that fails without the change. For this case it should not be hard to make. It is something I was hoping to get round to do sometime soon, but if you want to make a PR for that, I'd be happy to merge it (assuming the test passes, and the CLA is signed).

**Comment by ehx-v1** [comment]
Alrighty, the link towards "How to sign the CLA" can be found in #238.

**Comment by ehx-v1** [comment]
What I would imagine the test case like is creating a node, then check that it is in the index, remove the index node, and try-fail-catch to access the index node after removal. The try-fail-catch could also be packed into a method like `assertNodeNotExists(Node)`. My suggestion would be, @Infiniverse fixes the issue and I make the test case. Btw @craigtaverner which branch would you settle this in? It's definitely a 2.x issue, but I'm not quite sure how far back it's worth going...

**Comment by ehx-v1** [comment]
@pdtyreus already made a test case for REST API, so mine will only have to cover the Java API as far as I get it.

**Comment by craigtaverner** [comment]
I would think it is sufficient to fix this in the 0.15-neo4j-2.3 branch, but since that is very similar to 0.15-neo4j-2.2 it would be easy enough to fix back there and merge forward.

**Comment by ehx-v1** [comment]
My department has a "lab day" this Friday, so that's when I'll make the test together with my PR about OSMImporter refactoring.

**Comment by craigtaverner** [comment]
Super. Looking forward to seeing that!

**Comment by craigtaverner** [comment]
I believe I have fixed the node removal from index bug. Not as simple as the original suggestion, but that was a step in the right direction. See my commit (including test code) at https://github.com/neo4j-contrib/spatial/commit/f24ef823c87721831e2d4a3273fe01eacb802ff6

**Comment by thiagomorato** [comment]
@craigtaverner Where can I find more about these procedures you are referring to?

**Comment by craigtaverner** [comment]
I've started adding some minimal bits of information to the README, but we'd really like to update the complete spatial documentation to support this properly. We have some drafts of this, but nothing ready to go out. Right now the best I can suggest is, as now described in the readme:

* you can list the available procedures within Neo4j using the query `CALL spatial.procedures`
* you can look for examples in https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java

**Comment by ehx-v1** [comment]
Documenting this would most probably be part of re-establishing the wiki I guess?

**Comment by ehx-v1** [comment]
Also interesting how the former code demonstrates one broadly used horrible practice: Empty catch blocks. As usual, it's just there for "removing" errors one didn't want to deal with. The trouble is that the error is still there, it's only covered up, and might later screw up literally everything. Many people don't understand that, in most cases, exceptions are thrown for a reason. In my opinion, catch blocks should at very least contain `if (e instanceof RuntimeException) throw (RuntimeException)e;`. To be honest, I don't really understand how that code passed through the reviews.
Again, for everyone who didn't understand: I'm referring to the original code before the fix, quoted in the third comment.
However, I could imagine that @craigtaverner just ignored this flaw. (He's a good and experienced programmer, so that's nothing I would think if not for #239.) And I could imagine that this very same bad practice has more occurrences. So, what I'm asking is: **Is there a point in opening an issue about cleaning up empty catch blocks?**

**Comment by ctytgat** [comment]
@craigtaverner 
Hi, I don't see a procedure to remove a node from a layer. Am I missing something?
We need to do this through cypher, what is currently the correct way to do this?

**Comment by craigtaverner** [comment]
Hi, I've checked and you are right there is no such procedure. I'll look at adding one. In the meantime, it might work to simply delete the incoming RTREE_REFERENCE relationship from the node. This would remove it from the layer and index so it can no longer be found. However, it will not trigger an index rebalancing, so if you remove a lot of nodes you would end up with a weird index. In that case rather delete the layer and re-add only the nodes you need.

**Comment by ctytgat** [comment]
Thx, that would be helpful! Any estimate on when that would be available?
If we delete the relationship in the meantime, what would be the side effects of a 'weird index'? We need to delete and re-add nodes regularly...

**Comment by ctytgat** [comment]
An update (WKT) procedure seems to be missing as well. Can that also be added?

**Comment by craigtaverner** [comment]
I see there is a separate request to add a remove method at https://github.com/neo4j-contrib/spatial/issues/301. Should we close this issue and keep only the newer one?

**Comment by ctytgat** [comment]
That's ok, maybe add the update procedure to the other one as well then?

**Comment by craigtaverner** [comment]
Update is essentially just remove followed by add. I'll look and see if there are benefits to a dedicated update method.

**Comment by Zaryab-Arif** [comment]
In which environment this code can be extracted? It can be implemented in eclipse or netbeans? Is there any prerequisite for it? Is it compulsory to have a neo4j for only code implementation?

**Comment by craigtaverner** [comment]
The readme explains how to build this. You need java and maven, and all other dependencies will be pulled down by maven (including the relevant parts of Neo4j). We have in the past also used eclipse, and currently use intellij, but the IDE is not a requirement, only a convenience.

**Comment by Zaryab-Arif** [comment]
Hi @craigtaverner  I have some questions. Please check your slacks account. I have asked there.

**Comment by craigtaverner** [comment]
I just pushed two small releases that include the ability to remove nodes from layers. See 0.26.2 in https://github.com/neo4j-contrib/spatial/releases

The ability to remove layers was added in earlier releases.
