### ISSUE TITLE
How to Create Spatial Nodes in Cypher and does Spatial work with CSV Batch-Import?

### ISSUE THREAD

**Issue by 1manStartup** [neo4j-contrib/spatial#146]
Hello.

I would like to know if it is possible to create Spatial nodes in cypher (as I only see the REST method documented)?

Also is it possible to use match and search with neo4j 2.0 labels in spatial with cypher?

Finally is it possible to do batch-import and creation of spatial nodes in cypher? 

Thanks.

**Comment by craigtaverner** [comment]
It looks like this old question never got answered. Well, 4 years later this was possible after the 3.4 release of Neo4j you should be able to do this all with Neo4j itself. If that turns out to not be good enough for your needs, please ask again, and we'll try answer sooner this time!
