### ISSUE TITLE
Neo4j Spatial issue : findWithinDistance: ava.lang.IllegalArgumentException: Index with the same name but different config exists

### ISSUE THREAD

**Issue by nadir75** [neo4j-contrib/spatial#156]
Hello to all!

We need to locate a set of objects thanks to the geolocation in a defined radius distance.
We try to use Neo4J spacial library using SpatialRepository class to implement the method “findWithinDistance”

Bellow the used code for the implemntation with the the index type POINT to store longitude and latitude of the object :

@NodeEntity
@TypeAlias(value="MyObject")
public class MyObject{
    @GraphId Long nodeId;
    private String label;
    private String description;
    private Double lat;
    private Double lon;
     @Indexed(indexType = IndexType.POINT, indexName = "locations") String wkt;
       public void setLocation(float longitude, float latitude) {
          this.wkt = String.format("POINT( %.2f %.2f )",longitude,longitude);
       } 

1 ) For the first run we don’t have any problem to create the objects in neo4j database ( we can see the objects with the correct data in neo4j) For the second run or the creation of a new Object we have saying : index with the same name but different config exists
we don't know if we are talking about issue or problem of use..anyway :  

Infos: An exception was caught and reported. Message: java.lang.IllegalArgumentException: Index with the same name but different config exists! org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'objectRepositoryImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.springframework.data.neo4j.support.Neo4jTemplate fr.spart.is.neo4j.repository.ObjectRepositoryImpl.template; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'neo4jTemplate' defined in class org.springframework.data.neo4j.config.Neo4jConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.springframework.data.neo4j.support.Neo4jTemplate org.springframework.data.neo4j.config.Neo4jConfiguration.neo4jTemplate() throws java.lang.Exception] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'neo4jMappingContext' defined in class org.springframework.data.neo4j.config.Neo4jConfiguration: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Index with the same name but different config exists! at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:292) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475) at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195) at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703) at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)

2) Another point for the method that I have to implement findWithinDistance: we should make the template methods or Neo4j Cypher query to search objects?

Thank you for your help,

Do not hesitate if you need precisions

**Comment by ehx-v1** [comment]
I just begun using it myself, but it looks to me like in the second run it tries to re-create the index from the @Indexed, which leads to part 1
as for 2, I suppose generally it's when you started with the Java API then better stick with the Java API, so I would rather go for the template methods

**Comment by craigtaverner** [comment]
This looks like it might be using the old deprecated IndexProvider API. I also think this use case looks much better suited to the native points in Neo4j 3.4.
