### ISSUE TITLE
Missing type declaration in GeoPipesTest.java

### ISSUE THREAD

**Issue by mphizi** [neo4j-contrib/spatial#162]
Line 1159 of the file GeoPipesTest.java (org.neo4j.gis.spatial.pipes.GeoPipesTest) is missing the declaration for the variable "engine" leading to build errors with maven:

ExecutionEngine engine = new ExecutionEngine( db );

**Comment by craigtaverner** [comment]
Fixed by @jexp as part of #163, see commit b36609b1e1039d9abd5b066f035defa5256219fd. See
