### ISSUE TITLE
Precompiled build for Neo4j 2.2.x?

### ISSUE THREAD

**Issue by seenickcode** [neo4j-contrib/spatial#171]
Hello, could someone post a precompiled build for Neo4j 2.2.x and post it in the README?  Thanks in advance.

**Comment by amorgner** [comment]
Hi Nick,

precompiled builds of Neo4j Spatial are available here: https://github.com/neo4j-contrib/m2/tree/master/releases/org/neo4j/neo4j-spatial

**Comment by craigtaverner** [comment]
Since 2.2 is released, I assumed we can merge 0.14-2.2.0 into master now? I do not see any recent edits to either, so I assume there is nothing blocking this merge, unless axel has some local commits for 2.2?

**Comment by seenickcode** [comment]
@amorgner thanks!
