### ISSUE TITLE
Backup problem with spatial plugin installed

### ISSUE THREAD

**Issue by Jempan** [neo4j-contrib/spatial#181]
I am using Neo4j 2.2.1 with spatial plugin Neo4j-Spatial-0.14-neo4j-2.2.0.

Unfortunately the backup functionality does not work when I have the spatial plugin installed, it exits with "Exception in thread "main" java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/util/ResourceIterators at org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation.listStoreFiles<SpatialIndexImplementation.java:89>"

**Comment by craigtaverner** [comment]
It seems that access to ResourceIterators was added in January, and then the ResourceIterators was removed in March, so we need another solution, perhaps a local anonymous class, or revert to throwing the exception (previous behaviour before January edit).

See https://github.com/neo4j-contrib/spatial/commit/70142e1d76ae274cf19330bba09ca58270588dd6 (new call to ResourceIterators from spatial)
And https://github.com/neo4j/neo4j/commit/2ea51e3ec08457805d5cb5d7dfc8d57ef64709d6 (removal of ResourceIterators from kernel)

**Comment by jeremykendall** [comment]
Looks like #187 resolves this. Wink, wink, nudge, nudge ...

**Comment by craigtaverner** [comment]
Releases for neo4j 2.2.2 and 2.2.3 include the fix. See the README for download links.
