### ISSUE TITLE
0.14-neo4j-2.2.0 is not REST compatible with SDN 3.3.0.RELEASE on Neo4j 2.2.1 server mode

### ISSUE THREAD

**Issue by asompheng** [neo4j-contrib/spatial#183]
Hello,

As described in this post (http://stackoverflow.com/questions/30306498/compatibility-neo4j-spatial-with-spring-data-neo4j-rest-and-neo4j-ce-2-2-1-serve) , using spatial version 0.14-neo4j-2.2.0 with SDN 3.3.0 on neo4j 2.2.1, when I try to create a layer, I get the exception:

```
SEVERE: Servlet.service() for servlet [com.stampy.foundation.remote.RestConfiguration] in context with path [/myapp-server] threw exception [java.lang.RuntimeException: javax.servlet.ServletException: java.lang.NoSuchMethodError: org.neo4j.graphdb.GraphDatabaseService.execute(Ljava/lang/String;Ljava/util/Map;)Lorg/neo4j/graphdb/Result;] with root cause
java.lang.NoSuchMethodError: org.neo4j.graphdb.GraphDatabaseService.execute(Ljava/lang/String;Ljava/util/Map;)Lorg/neo4j/graphdb/Result;
    at org.neo4j.gis.spatial.utilities.ReferenceNodes.getReferenceNode(ReferenceNodes.java:43)
    at org.neo4j.gis.spatial.SpatialDatabaseService.getSpatialRoot(SpatialDatabaseService.java:78)
    at org.neo4j.gis.spatial.SpatialDatabaseService.getLayer(SpatialDatabaseService.java:114)
    at org.neo4j.gis.spatial.SpatialDatabaseService.getOrCreateLayer(SpatialDatabaseService.java:208)
```

Spatial is calling not anymore existing method execute(...) in class ReferenceNodes org.neo4j.gis.spatial.utilities.ReferenceNodes.getReferenceNode(ReferenceNodes.java:43)

**Comment by ehx-v1** [comment]
that's strange, because I, though only recently having included Spatial, already worked quite a while with Neo4j 2.3.0, where execute(query) is right there (I know because I made a wrapper GraphDatabaseService), and from what you say it also existed some releases earlier so it should also exist between the releases, so also in 2.2.1?

**Comment by craigtaverner** [comment]
I'm assuming this issue is no longer valid. Please re-open if this issue occurs with newer versions.
