### ISSUE TITLE
Upgrade to neo4j 2.2.2

### ISSUE THREAD

**Issue by darabi** [neo4j-contrib/spatial#186]
Latest release version of neo4j is 2.2.2. Would it be possible to compile and test against that release and release a new version?

**Comment by craigtaverner** [comment]
Could you sign the CLA as described at http://neo4j.com/docs/stable/community-contributing.html. Then we could merge your PR.

**Comment by darabi** [comment]
Done.

**Comment by amorgner** [comment]
There are spatial releases for Neo4j 2.2.2, 2.2.3 and 2.2.4 (https://github.com/neo4j-contrib/m2/tree/master/releases/org/neo4j/neo4j-spatial), so closing this issue.
