### ISSUE TITLE
Can I install this with one command?

### ISSUE THREAD

**Issue by ccorcos** [neo4j-contrib/spatial#191]
That would be awesome. Also, is there a database-as-a-service that supports these spatial queries?

**Comment by jexp** [comment]
GrapheneDB.com provides the spatial plugin in their plans

You can install by unzipping the spatial.zip to path/to/neo4j/plugins

see: https://github.com/neo4j-contrib/spatial#using-the-neo4j-spatial-server-plugin

When released by @amorgner the 2.2.4 plugin will be here:

https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.15-neo4j-2.2.4/neo4j-spatial-0.15-neo4j-2.2.4-server-plugin.zip?raw=true

**Comment by amorgner** [comment]
I released the new spatial version from the 0.14-neo4j-2.2 branch, so it's actually here:

https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.14-neo4j-2.2.4/neo4j-spatial-0.14-neo4j-2.2.4-server-plugin.zip?raw=true

**Comment by ccorcos** [comment]
So there are no services that do all this for me? I guess I'm going to have to get my hands dirty :/

**Comment by samcorcos** [comment]
Or you could use graphene!

**Comment by ccorcos** [comment]
> GrapheneDB.com provides the spatial plugin in their plans

*plans*

**Comment by samcorcos** [comment]
Plans?

**Comment by ccorcos** [comment]
they dont support it yet

**Comment by amorgner** [comment]
They do. There are three commercial plans: Hobby, Standard, Performance, even the smallest plan supports the spatial plugin.

**Comment by samcorcos** [comment]
@ccorcos There you go!

**Comment by amorgner** [comment]
BTW, Structr (https://github.com/structr/structr) has also Neo4j spatial built-in. You can do things like ``GET locations?distance=5&address=1+Market+St+San+Francisco`` and it will find you all things within 5 km radius of that address.

**Comment by ccorcos** [comment]
@amorgner whoa, how loosely is the address interpreted? I'm assuming this works with latitude and longitude as well?

**Comment by amorgner** [comment]
The address is looked up/converted into coords by a (configurable) geocoding provider, currently supported are Google and Bing.

**Comment by ccorcos** [comment]
oh sweet!
