### ISSUE TITLE
Spatial index gets corrupted whilst importing duplicate point data

### ISSUE THREAD

**Issue by Infiniverse** [neo4j-contrib/spatial#192]
I'm experiencing issues importing some point data into a spatial index.
I'm getting exceptions of the form:

```org.neo4j.graphdb.NotFoundException: More than one relationship[RTREE_CHILD, INCOMING] found for Node[2091198]```

After importing 101 instances nodes of the form:

```{ wkt: POINT (51.30979919433594 -2.451493978500366) }```

The following test fails:

```match (:ReferenceNode)-->({layer:"test"})-[*]->(n) where not n-->()
WITH n
match n<-[:RTREE_REFERENCE]-m
WITH n, collect(m) as ms
WHERE length(ms) > 1
return count(n) = 0```

i.e. there are nodes doubly linked into the spatial graph.

**Comment by Infiniverse** [comment]
Ok, found the problem. The quadraticSplit in the RTree code was selecting the same node for both the left and right sides of a RTree split! Oops!

Pull request #193 fixes the problem.

**Comment by Infiniverse** [comment]
The fix has been merged.

**Comment by jexp** [comment]
Thanks a lot @Infiniverse !!
