### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by rileycrane** [neo4j-contrib/spatial#202]
The README contains a type that makes it hard to install this plugin.

In particular the lines around [install the plugin](https://github.com/neo4j-contrib/spatial/blame/master/README.md#L228) should read
```
    #install the plugin
    cp $NEO4J_SPATIAL_HOME/target/neo4j-spatial-XXXX-server-plugin.zip $NEO4J_HOME/plugins
    cd $NEO4J_HOME/plugins
    unzip neo4j-spatial-XXXX-server-plugin.zip -d $NEO4J_HOME/plugins
```

**Comment by craigtaverner** [comment]
Thanks for the advice. Now I've make it more correct as part of a minor cleanup of that section.
