### ISSUE TITLE
what is the official way to remove a node from a spatial index?

### ISSUE THREAD

**Issue by tobias74** [neo4j-contrib/spatial#203]
I am trying to remove a node from the spatial index, but I cannot find anything in the manual.
Can anybody help?

Thanks :-)

**Comment by craigtaverner** [comment]
It depends on the API that you are using:

* The richest API is the Java embedded API, then the you can use the layer.delete(nodeid) call. (See https://github.com/neo4j-contrib/spatial/blob/0.15-neo4j-2.3/src/test/java/org/neo4j/gis/spatial/TestSimplePointLayer.java#L143)
* If you added nodes using the IndexProvider, you would probably have to delete and create the nodes.
* If it is the REST API, then there are no explicit functions for this, and you would have to either:
  * Write a delete method to the REST API (improve Neo4j Spatial)
  * Create some service side code to do this through the Java API (write you own extension)
  * Use a Cypher command that understood the graph model and how your node was connected to the index and deleted that connection (usually relationship of type RTREE_REFERENCE)

This last option might be easiest, with a command something like:
```
MATCH (n:Geom {id:{id}})<-[r:RTREE_REFERENCE]-() DELETE r
```
