### ISSUE TITLE
How to create new spatial database from multiple csv files?

### ISSUE THREAD

**Issue by mpeniak** [neo4j-contrib/spatial#204]
Hi guys,

I am new to neo4j and to neo4j spatial. I have a set of csv files that describe nodes and relationships. I used these in the past to create a standard neo4j database. However, I have latitudes and longitudes for around 35 million nodes and therefore I would like to use neo4jspatial so that I can then do spatial queries.

What are the steps to build this spatial database please? Do I need to just rebuild everything and create a spatial index for these 35 million nodes or do I just create a spatial index on top of existing database?

**Comment by craigtaverner** [comment]
The design of neo4j spatial was specifically to allow you to be able to re-use your existing data model, where possible. However this depends on a few things:

* You are accessing Neo4j and Neo4j Spatial through the embedded Core API (ie. in Java)
* Your model matches one of the existing GeometryEncoder's included
* Or you are willing to write a GeometryEncoder to match your model

In your case if you have nodes with latitude and longitude properties of type 'double', then you can use the SimplePointGeometryEncoder, which is provided by the SimplePointLayer. Just create a layer of that type, and then add the nodes to the layer. See, for example, the code in the test case at:

https://github.com/neo4j-contrib/spatial/blob/0.15-neo4j-2.3/src/test/java/org/neo4j/gis/spatial/TestSimplePointLayer.java#L143

**Comment by mpeniak** [comment]
Thanks Craig, very helpful reply!
