### ISSUE TITLE
Routing on OSM Data

### ISSUE THREAD

**Issue by boldtrn** [neo4j-contrib/spatial#208]
Hi,

I'd like to create routes using OSM data and neo4j. Currently I am considering this plugin. Is this plugin beneficial for routing and is this plugin available for embeded databases?

Thanks in advance,
Robin

**Comment by craigtaverner** [comment]
The spatial library can be used for routing and is in fact primarily for
embedded use. However the OSM importing functionality builds a full OSM
graph, which is far more than you need to route with, and will not perform
well for routing. You should rather write your own importer that imports
only the waypoints relevant to routing, like intersection points. Then use
something like A* to route on that.

**Comment by themmes** [comment]
@craigtaverner It will not perform well because of additional non-intersection nodes in road segments? Or are there other reasons for it not to perform on routing?

**Comment by craigtaverner** [comment]
@themmes Correct. The primary issue will be that there will be a much, much longer path to route over if all OSM nodes are included. There are other more subtle issues though, like the fact that the OSM model does not clearly include turning restrictions, and you might want to add those for better routing. Another option to consider is creating a layered graph model with long distance routing in city-city graph for first approximation routing, followed by fine grained routing on the OSM model itself.
