### ISSUE TITLE
Issue with: mvn clean package - against Neo4j 3.0.0-M03 

### ISSUE THREAD

**Issue by shainefisher** [neo4j-contrib/spatial#220]
Actually the issue is with the build against ANY version, so it is likely to be an issue with my setup. I was originally running an instance of 2.3.0 and 2.3.2, I downloaded the pre-compiled versions and unpacked then to the root of the plugins folder, and after starting the server the extension was not listed, and could not be called through the rest api.
I saw a post on building it yourself solving this issue but when I downloaded Neo4j 3.0 and installed it (upgrading the older version store) and then download as zip the spatial-master, running mvn clean package, or mvn install, results in this error, which is somewhat unhelpful.
Windows 10 Professional, 64bit.

java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) Client VM (build 25.66-b18, mixed mode, sharing)
---
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ neo4j-spatial ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 162 source files to C:\Users\shain\Downloads\spatial-master\spatial-master\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[34,25] cannot find symbol
  symbol:   class ReturnableEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[35,25] cannot find symbol
  symbol:   class StopEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[37,25] cannot find symbol
  symbol:   class TraversalPosition
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[38,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java:[55,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java:[62,35] package org.neo4j.index.impl.lucene does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[25,31] cannot find symbol
  symbol:   class IndexImplementation
  location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[29,31] cannot find symbol
  symbol:   class IndexCommandFactory
  location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[30,31] cannot find symbol
  symbol:   class LegacyIndexProviderTransaction
  location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[33,49] cannot find symbol
  symbol:   class CommandHandler
  location: package org.neo4j.kernel.impl.transaction.command
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[35,52] cannot find symbol
  symbol: class IndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[55,58] cannot find symbol
  symbol:   class IndexCommandFactory
  location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[55,12] cannot find symbol
  symbol:   class LegacyIndexProviderTransaction
  location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[77,12] cannot find symbol
  symbol:   class CommandHandler
  location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/pipes/osm/processing/ExtractOSMPoints.java:[31,24] cannot find symbol
  symbol:   class OrderedByTypeExpander
  location: package org.neo4j.kernel
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[34,25] cannot find symbol
  symbol:   class ReturnableEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[35,25] cannot find symbol
  symbol:   class StopEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[37,25] cannot find symbol
  symbol:   class TraversalPosition
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[38,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[28,25] cannot find symbol
  symbol:   class ReturnableEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[29,25] cannot find symbol
  symbol:   class StopEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[30,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[266,50] cannot find symbol
  symbol:   class ReturnableEvaluator
  location: class org.neo4j.gis.spatial.rtree.RTreeIndex
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[266,71] cannot find symbol
  symbol:   class StopEvaluator
  location: class org.neo4j.gis.spatial.rtree.RTreeIndex
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[276,36] cannot find symbol
  symbol:   class TraversalPosition
  location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[292,49] cannot find symbol
  symbol:   class TraversalPosition
  location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[298,43] cannot find symbol
  symbol:   class TraversalPosition
  location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[27,25] cannot find symbol
  symbol:   class ReturnableEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[28,25] cannot find symbol
  symbol:   class StopEvaluator
  location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[29,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[23,31] cannot find symbol
  symbol:   class IndexProviders
  location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[33,9] cannot find symbol
  symbol:   class IndexProviders
  location: interface org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.Dependencies
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[44,23] cannot find symbol
  symbol:   class IndexProviders
  location: class org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.SpatialKernelExtension
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[47,39] cannot find symbol
  symbol:   class IndexProviders
  location: class org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.SpatialKernelExtension
[INFO] 34 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:24 min
[INFO] Finished at: 2016-02-10T11:44:47+00:00
[INFO] Final Memory: 34M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project neo4j-spatial: Compilation failure: Compilation failure:
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[34,25] cannot find symbol
[ERROR] symbol:   class ReturnableEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[35,25] cannot find symbol
[ERROR] symbol:   class StopEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[37,25] cannot find symbol
[ERROR] symbol:   class TraversalPosition
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[38,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java:[55,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMImporter.java:[62,35] package org.neo4j.index.impl.lucene does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[25,31] cannot find symbol
[ERROR] symbol:   class IndexImplementation
[ERROR] location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[29,31] cannot find symbol
[ERROR] symbol:   class IndexCommandFactory
[ERROR] location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[30,31] cannot find symbol
[ERROR] symbol:   class LegacyIndexProviderTransaction
[ERROR] location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[33,49] cannot find symbol
[ERROR] symbol:   class CommandHandler
[ERROR] location: package org.neo4j.kernel.impl.transaction.command
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[35,52] cannot find symbol
[ERROR] symbol: class IndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[55,58] cannot find symbol
[ERROR] symbol:   class IndexCommandFactory
[ERROR] location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[55,12] cannot find symbol
[ERROR] symbol:   class LegacyIndexProviderTransaction
[ERROR] location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialIndexImplementation.java:[77,12] cannot find symbol
[ERROR] symbol:   class CommandHandler
[ERROR] location: class org.neo4j.gis.spatial.indexprovider.SpatialIndexImplementation
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/pipes/osm/processing/ExtractOSMPoints.java:[31,24] cannot find symbol
[ERROR] symbol:   class OrderedByTypeExpander
[ERROR] location: package org.neo4j.kernel
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[34,25] cannot find symbol
[ERROR] symbol:   class ReturnableEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[35,25] cannot find symbol
[ERROR] symbol:   class StopEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[37,25] cannot find symbol
[ERROR] symbol:   class TraversalPosition
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/osm/OSMDataset.java:[38,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[28,25] cannot find symbol
[ERROR] symbol:   class ReturnableEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[29,25] cannot find symbol
[ERROR] symbol:   class StopEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/encoders/SimpleGraphEncoder.java:[30,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[266,50] cannot find symbol
[ERROR] symbol:   class ReturnableEvaluator
[ERROR] location: class org.neo4j.gis.spatial.rtree.RTreeIndex
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[266,71] cannot find symbol
[ERROR] symbol:   class StopEvaluator
[ERROR] location: class org.neo4j.gis.spatial.rtree.RTreeIndex
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[276,36] cannot find symbol
[ERROR] symbol:   class TraversalPosition
[ERROR] location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[292,49] cannot find symbol
[ERROR] symbol:   class TraversalPosition
[ERROR] location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java:[298,43] cannot find symbol
[ERROR] symbol:   class TraversalPosition
[ERROR] location: class org.neo4j.gis.spatial.rtree.RTreeIndex.SearchEvaluator
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[27,25] cannot find symbol
[ERROR] symbol:   class ReturnableEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[28,25] cannot find symbol
[ERROR] symbol:   class StopEvaluator
[ERROR] location: package org.neo4j.graphdb
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/OrderedEditableLayer.java:[29,35] package org.neo4j.graphdb.Traverser does not exist
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[23,31] cannot find symbol
[ERROR] symbol:   class IndexProviders
[ERROR] location: package org.neo4j.graphdb.index
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[33,9] cannot find symbol
[ERROR] symbol:   class IndexProviders
[ERROR] location: interface org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.Dependencies
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[44,23] cannot find symbol
[ERROR] symbol:   class IndexProviders
[ERROR] location: class org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.SpatialKernelExtension
[ERROR] /C:/Users/shain/Downloads/spatial-master/spatial-master/src/main/java/org/neo4j/gis/spatial/indexprovider/SpatialKernelExtensionFactory.java:[47,39] cannot find symbol
[ERROR] symbol:   class IndexProviders
[ERROR] location: class org.neo4j.gis.spatial.indexprovider.SpatialKernelExtensionFactory.SpatialKernelExtension
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Any ideas how to solve this and build against Neo4j 3.0? Thanks

**Comment by craigtaverner** [comment]
At first glance I think the errors you are getting are related to the fact that 3.0 has removed a number of long deprecated API's that Neo4j Spatial was relying on. The spatial library was written back in the early 1.x days of Neo4j, and so needs to be refactored to the newer API's. This is probably non-trivial work.

Have you tried building against 2.3.1? I would not expect these errors there.

**Comment by shainefisher** [comment]
I will give it a go, thanks.

**Comment by shainefisher** [comment]
No, that was a bust, but  have a lightly better question. What version of spatial will work with which version of Neo4j? For example, there are precompiled version for Neo4j 2.3.0 (https://github.com/neo4j-contrib/m2/blob/master/releases/org/neo4j/neo4j-spatial/0.15-neo4j-2.3.0/neo4j-spatial-0.15-neo4j-2.3.0-server-plugin.zip?raw=true) and there appears to be one for 2.3.1 as well that isn't listed, but what is the *maximum* version they will run under or are they truly version specific?

**Comment by baking1** [comment]
Having exactly the same problem as shainfisher - how would I build against 2.3.1?

**Comment by zavan** [comment]
I was able to build against 2.3.2 (haven't tested yet, but the build was successful) by changing the neo4j version in `pom.xml` and removing `@Documented` references from tests.

I've forked the repository and commited those changes to [this branch](https://github.com/zavan/spatial/tree/build-against-2.3.2).
You can clone the repo, checkout to the branch and run `mvn install` to build.

You can check what I changed [here](https://github.com/zavan/spatial/compare/master...build-against-2.3.2).

**Comment by shainefisher** [comment]
If you have a working version for 2.3.2 would you be prepared to make it available for download to me please?
I still can't build it, for different errors than before but the same rule applies. It really shouldn't be this hard to build something to test. I know it's likely my setup, but still, it works for everything else.
If there was an alternative I would be trying that, but it appears there is no other add-on that provides these features, and these are amazing features.

**Comment by zavan** [comment]
@shainefisher You can download my compressed "target" dir [here](https://drive.google.com/file/d/0B-XOwKzGTq9XRlhoWGtJWUIwRUE/view?usp=sharing). I can't garantee it will work on your machine, but it probably will. Built on Ubuntu 15.10 x64 desktop against [my branch](https://github.com/zavan/spatial/tree/0.15-neo4j-2.3.2).

**Comment by shainefisher** [comment]
No sadly it didn't work, thank though.

I will wait until someone builds one for 2.3.2 and adds a link to the readme. I surrender.

**Comment by ehx-v1** [comment]
no idea about whether it's possible to convert a JAR into a Geoserver plugin, but if it is you could try importing Spatial into Eclipse and then using that JAR to make the plugin
(if that's bullshit sorry, I have very little idea of Geoserver)

**Comment by shainefisher** [comment]
resolved for 2.3.2 and 2.3.3, thanks all.
