### ISSUE TITLE
Index `geom` does not exist when execute SpatialQuery with  CypherQL

### ISSUE THREAD

**Issue by geosmart** [neo4j-contrib/spatial#227]
When I run cypher in neo4j browser

``` sql
profile start n = node:geom('withinDistance:[31.331937,120.638154,1.0]')
match (n)
where  (labels(n) in ['POI','STR'])  
return n
```

'Index `geom` does not exist' Error throws!
but when I run java testCase to test the Spatial query ,everythin is OK!

``` java
  @Test
  public void test_SpatialQuery_Buffer() {
    try (Transaction tx = graphDatabaseService.beginTx()) {
      LayerNodeIndex layerIndex = new LayerNodeIndex("geom", graphDatabaseService, config);

      // [y,x] rather than [x,y]
      Double[] coords = new Double[] {31.330263d, 120.684968d};
      Map<String, Object> params = new HashMap<String, Object>();

      params.put(LayerNodeIndex.POINT_PARAMETER, coords);
      params.put(LayerNodeIndex.DISTANCE_IN_KM_PARAMETER, 1.0);

      IndexHits<Node> hits = layerIndex.query(LayerNodeIndex.WITHIN_DISTANCE_QUERY, params);
      for (Node spatialNode : hits) {
        Node dbNode = graphDatabaseService.getNodeById(spatialNode.getId());
        System.out.println(spatialNode.getId());
        for (String key : dbNode.getPropertyKeys()) {
          System.out.println(key + " " + dbNode.getProperty(key));
        }
        System.out.println("******\n");
      }
    }
  }
```

I create the spatial index  like this

``` java
 @Autowired
  GraphDatabaseService graphDatabaseService;

  final Map<String, String> config = new HashMap<String, String>();

  @Before
  public void setup() {
    System.out.println("---setup----");
    config.put(LayerNodeIndex.LAT_PROPERTY_KEY, "lati");
    config.put(LayerNodeIndex.LON_PROPERTY_KEY, "long");
    config.put(SpatialIndexProvider.GEOMETRY_TYPE, LayerNodeIndex.POINT_PARAMETER);
  }

  @Test
  public void test_createAddressNodeSpatialIndex() {
    try (Transaction tx = graphDatabaseService.beginTx()) {
      LayerNodeIndex layerIndex = new LayerNodeIndex("geom", graphDatabaseService, config);

      ResourceIterator<Node> nodes = graphDatabaseService.findNodes(DynamicLabel.label("AddressNode"));
      while (nodes.hasNext()) {
        Node node = nodes.next();
        Object lon = node.getProperty("long", null);
        Object lat = node.getProperty("lati", null); 
        if (lon != null && lat != null) { 
          layerIndex.add(node, "", "");
        }
      }
      tx.success();
    }
  }
```

I need to combined Spatial Query with Node Property Filter and pagination  result.
so Cypher is my only choice!

Any Help With Be Appreciate!

**Comment by geosmart** [comment]
I use Neo4j 2.3.3 Enterprise  windows ,
Neo4j Spatial  Plugin Version is  `neo4j-spatial-0.15-neo4j-2.3.3-server-plugin`
``` json
:GET /db/data/ext
{
  "SpatialPlugin": "http://localhost:7474/db/data/ext/SpatialPlugin"
}
```

**Comment by geosmart** [comment]
I read the Neo4j Spatial source code (IndexProviderTest) to create index  with __SpatialIndexProvider.SIMPLE_POINT_CONFIG__,and  __index geom does not exist__ error disappeard.

testcase
[NewNeo4jSpatialTest.java](https://gist.github.com/geosmart/9456d26a926c3bfddca50944eed0282f)

**Comment by ehx-v1** [comment]
While most "index does not exist" issues result from the index style disambiguation, as described in #247, your last update makes this look more like you try to use an invalid config. Also, I've never seen `@Autowired` before. Perhaps it does something wrong?
Side note: As for coordinate order, it's exactly the other way. This version of `withinDistance` is the only part of Neo4j Spatial expecting the coordinates to be latitude first. In all of the other instances, including the entire Java API, longitude comes first. You may want to check this, because it looks like you always put latitude into long and longitude into lati, which means your entire map would be flipped.

**Comment by craigtaverner** [comment]
The REST API is deprecated, and the use of the IndexProvider API was removed as far back as the releases for Neo4j 3.0. Please try the procedures instead, as they should work a lot better for you.
