### ISSUE TITLE
Spatial Data with Cypher

### ISSUE THREAD

**Issue by daniloboechat** [neo4j-contrib/spatial#228]
Is it possible to insert spatial data with cypher using the neo4j web console? I can not find information about it. 

I'd like to create spatial nodes and indexes using cypher.

**Comment by ehx-v1** [comment]
that's what the Server Plugin should do I suppose, however I can't find a Spatial Cypher refcard either...
wondering why one might need that though, except if you want to use Neo4j in your general JDBC-based interface
btw is there such thing as auto-conversion to a RDBMS, so you can port it e.g. to Oracle DB easily? no use case of mine, just interest and also thinking it might be of use for others

**Comment by ehx-v1** [comment]
in the web console you can use `:GET` though, just don't forget to let out the `http://localhost:7575` in the URL, it's only `/db/...` when using `:GET` from the browser

**Comment by ehx-v1** [comment]
as you can see from the examples, the "TBD" is not up to date, as you can obviously access all JTS queries via Cypher
and the "TDB" for JSON queries is meant to be "TBD" too I suppose, and is neither up to date as you can just call Cypher via JSON (like in the REST examples for Cypher)

**Comment by ehx-v1** [comment]
one could ask for the Neo4j Browser to be able to display REST-response JSON, but that's just some subtleties

**Comment by craigtaverner** [comment]
In Neo4j 3.0 you can use procedures to work on spatial data from inside Cypher. The master branch already has a bunch in place, and hopefully we'll make a maven artifact available, and publish pre-build spatial plugins with this support. To get an idea of what is possible so far, take a look at the test code at https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java

**Comment by craigtaverner** [comment]
Neo4j 3.4 released much improved support for points within the database itself. In addition the procedures we provide in this library have gotten better over time.
