### ISSUE TITLE
Shocking amount of warnings, especially deprecation

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#239]
Upon working on Neo4j Spatial (freshly forked just today),  I stumbled over that there is an immense ton of warnings - almost 150 in sum!
While "raw type" and "unused" aren't worrying me much, one warning type looks like a serious problem: The "deprecation" warnings. They are only raised when the code uses deprecated methods or classes, but the snippet itself is not marked as deprecated. In many cases, it's code people simply forgot to directly annotate with `@Deprecated`, thinking `@deprecated` in the Javadoc would be enough. However, this is a fallacy, because I know a lot of people who never read the Javadoc. A warning is something everyone using an IDE will instantly spot, and additionally many IDEs highlight deprecated code as crossed out, which is even harder to overlook.
But both for a warning and for the cross-out, only the in-code `@Deprecated` counts, not the Javadoc `@deprecated`. So, someone should take care of that all the deprecated code is properly annotated - BEFORE people start running into bugs because they use deprecated code.

**Comment by ehx-v1** [comment]
Of course, you decide how urgent it is, but I'd strongly recommend to do it, and do it as soon as possible.

**Comment by ehx-v1** [comment]
After experimenting a little with the  Eclipse problem log settings, I found out there are 39 deprecation warnings. Don't know what you feel like, but to me that amount is a little frightening.

**Comment by jexp** [comment]
The Neo4j APIs aggressivly deprecate things also as "documentation" that there will be changes even if there are no alternatives yet.

So not all the things you saw are actually fixable, but I think many of them are.

**Comment by craigtaverner** [comment]
Many of the things Neo4j deprecated in 1.x, 2.x and 3.x might finally actually be removed in 4.0. I think we will only really get past this once we port to 4.0, which is a tricky job since it seems likely to remove features we rely heavily on (like the explicit lucene indexes).
