### ISSUE TITLE
OrthodromicDistance: replace Spherical Law formula by Vincenty formula?

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#240]
On having a closer look into code (figuring out what exactly the spatial queries do) I noticed that OrthodromicDistance pipes use this formula:
`d = acos(sin(lat1) * sin(lat2) + cos(lat1) * cos(lat2) * cos(lon2 - lon1)) * R`
After some research I found out it's the Spherical Law of Cosines. However, upon research I also discovered the Vincenty formula and would suggest switching to this formula, because from what it says in [this article](http://www.catalina-capri-25s.org/tech/latlongcalc.asp) it would probably be better (it's more precise than Haversine, after all!).
If you say that would be worth it, I can work it out and submit a pull issue. However, I'm not quite experienced in spatial queries and geocoding generally, so I'm not sure if switching to Vincenty would be appropriate for the use case. So tell me: Shall I go for it, or doesn't Vincenty fit the needs?

**Comment by ehx-v1** [comment]
Why I rose this question is basically: From what I understood in the article, Vincenty has better precision than Haversine, which in turns is more precise than Spherical Law. However, the code does seem to get more complicated. I'm not sure what, i.e. how drastic, the consequences for performance are. Perhaps you, being experienced programmers and geocoders, can judge that from the code, or already made some experience along these lines?

**Comment by craigtaverner** [comment]
Since Neo4j Spatial includes geotools libraries, we could defer the distance calculation to them, and handle all projections correctly.

**Comment by ehx-v1** [comment]
Ah, the todo. I'm getting it.

**Comment by ehx-v1** [comment]
Forgot to close.
