### ISSUE TITLE
test cases don't fulfill one test per method convention

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#241]
In JUnit testing, it's generally a convention to make one test per method only. Instead, you should have several test methods. This is a convention because otherwise JUnit cannot identify the test as independant test cases, thus you cannot know in which actual test the fail occurred. However, from what I saw, none of the Neo4j Spatial test classes fulfills this convention. Instead, they mostly have one single test method containing all the tests. For example, TestSpatialQueries has four independant test cases that only share the test data.
My suggestion would be stuffing the test data into private fields initialized in the constructor (which the JUnit API must use, it's the only way to instantiate any object, yes even `Class.newInstance()` searches for a nullary constructor, and an object is needed to call any methods after all) and each test case would get its own test method.
Even if there was a way to bypass the constructor, it would make perfectly no sense for a framework like JUnit because - well, for exactly that reason: Users of the framework might want to initialize their test data somewhere. And where to do that, except for the constructor of the test class? I think we should try.
Of course, I have pretty little idea of the dimension of such a whole test rewamp. It might result into loads of work. Also, why I ask (and don't just prepare a pull request) is that I'm not fully convinced that I'm going to understand the tests enough to separate the test cases from one another. Some test classes appear to be far more complicated than what I'm used to seeing from tests.

**Comment by craigtaverner** [comment]
I understand and agree with your concerns. The issue with the spatial testing is partly historical. The first draft of the code was written without classical test cases, at least not tests written in Junit, and as a consequence not committed to the code base. Then as a second round, higher level, integration tests were written. These would test a lot more than any unit test would, and provided the safetly we needed to protect against regressions, while not providing the coverage that unit tests provided. This was a big improvement, but obviously not as good as we'd really like. Later extensions to the library did include more test coverage, but there is still an opportunity to improve a lot, as you observed.

We would certainly welcome any PR including additional tests cases, both unit and integration tests. This is probably done best by targeting areas of interest and writing tests specific to those. Attempting a blanket improvement is probably not practical.

**Comment by ehx-v1** [comment]
I feel like starting to understand that there are style problems that may be easy to clean out in a solitary or Scrum-organized project, but which a large open source project simply has to somehow deal with...

**Comment by danchoi123** [comment]
<a href="http://daotaoketoan.top/hoc-ke-toan-tai-le-trong-tan-thanh-xuan-i844.html">học kế toán tại Thanh Xuân</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-cau-giay-i853.html">hoc ke toan tai cau giay</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-long-bien-i848.html">học kế toán tại Long Biên</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-ha-dong-i852.html">học kế toán tại Hà Đông</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-minh-khai-hai-ba-trung-i845.html">hoc ke toan tai minh khai</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-quan-dong-da-i936.html">hoc ke toan tai dong da</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-bac-ninh-i843.html">học kế toán tại Bắc Ninh</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-quan-thu-duc-i827.html">hoc ke toan tai thu duc</a> ban
<a href="http://daotaoketoan.top/khoa-hoc-ke-toan-tong-hop-thuc-hanh-tai-tphcm-i828.html">hoc ke toan tai tphcm</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-nguyen-chi-thanh-quan-dong-da-i897.html">trung tam ke toan tai dong da</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-minh-khai-hoang-mai-i846.html">lớp học kế toán tại minh khai</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-day-ke-toan-thuc-hanh-tai-cau-giay-i565.html">trung tâm kế toán tại từ liêm</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-ha-dong-i563.html">đào tạo kế toán tại hà đông</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-ke-toan-tai-le-trong-tan-i561.html">học kế toán tại lê trọng tấn</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-long-bien-i564.html">Học kế toán thực tế tại Long Biên</a> ban
<a href="http://trungtamketoanhn.com/khoa-hoc-ke-toan-tong-hop-thuc-hanh-thuc-te-o-bac-ninh-i660.html">trung tâm kế toán bắc ninh</a> ban
<a href="http://trungtamketoanhn.com/khoa-hoc-ke-toan-tong-hop-tai-tphcm-i599.html">trung tâm kế toán tphcm</a> ban
<a href="http://trungtamketoanhn.com/hoc-ke-toan-thuc-hanh-tai-thu-duc-i864.html">học kế toán tại thủ đức</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thu-duc-i1161.html">lớp học kế toán tại thủ đức</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-minh-khai-hai-ba-trung-i1142.html">lớp học kế toán tại minh khai</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-viet-hung-long-bien-i751.html">lớp học kế toán tại long biên</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-quang-trung-ha-dong-i750.html">kế toán hà nội 200 quang trung</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-le-trong-tan-i753.html">lớp học kế toán tại thanh xuân</a> ban
<a href="http://hocketoanvn.com/lop-hoc-ke-toan-tong-hop-thuc-hanh-tai-bac-ninh-i709.html">lớp học kế toán tại bắc ninh</a> ban
<a href="http://hocketoanvn.com/lop-hoc-ke-toan-tong-hop-thuc-te-tai-tphcm-i713.html">lớp học kế toán tại q3</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-hai-phong-i734.html">lớp học kế toán tại hải phòng</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-binh-duong-i831.html">lớp học kế toán tại bình dương</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-hai-duong-i814.html">lớp học kế toán tại hải dương</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">xkld macau</a> ban 
<a href="http://anhngunewlight.edu.vn/chi-nhanh-cong-ty-xkld-thang-long-a2117.html">công ty XKLĐ Thăng Long</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-bac-giang-i650.html">Công Ty XKLĐ Bắc Giang</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-hai-duong-i651.html">Công Ty XKLĐ Hải Dương</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-phu-tho-i653.html">Công ty XKLĐ tại Phú Thọ</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-vinh-phuc-i660.html">Công ty XKLĐ tại Vĩnh Phúc</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-thanh-hoa-i661.html">Công ty XKLĐ tại Thanh Hóa</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-hung-yen-i662.html">Công ty XKLĐ tại Hưng Yên</a> ban
