### ISSUE TITLE
Geopipe nearest neighbor search should contain the minimum extraction

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#242]
I'm currently having a look at GeoPipeline search implementations, especially the nearest neighbor search. I have seen that in the tests, the resulting GeoPipeline is first sorted by, then reduced to the minimum of the newly calculated property `Distance`. This is neccessary to be done so, considering the current implementation. However, isn't this operation actually part of the search? Shouldn't it be done in the `geoPipeline.startNearestNeighborSearch(...)` methods?

**Comment by ehx-v1** [comment]
Same for `geoPipeline.startNearestNeighborLatLonSearch(...)`.

**Comment by craigtaverner** [comment]
Where is the code you are looking at? Which test class and method?

**Comment by ehx-v1** [comment]
The test is `TestSpatialQueries`, and I also viewed the implementation because I very likely will need to inherit from `GeoPipeline` in order to make a custom pipe that applies multiple filters in a particular order.
As we both know, `TestSpatialQueries` has one large test method only (in #241 you told me one must get along with that somehow, remember?) but it doesn't matter in this case, because the `sort("Distance").getMin("Distance")` operation is applied every time. I strongly assume this is generally so, and would consider this operation rather part of the search than of the code around it, also because the method name implies that this is already done.

**Comment by danchoi123** [comment]
<a href="http://ketoanthucte.top/viet-email-xin-viec-hay-nhat-i1462.html">viet email xin viec</a> ban
<a href="http://ketoanthucte.top/muc-tieu-nghe-nghiep-trong-cv-xin-viec-i1461.html">muc tieu nghe nghiẹp</a> ban
<a href="http://ketoanthucte.top/tim-viec-lam-them-cho-sinh-vien-i1153.html">viec lam them</a> ban
<a href="http://ketoanthucte.top/thong-tu-95-2016-tt-btc-a2151.html">thong tu 95/2016/btc</a> ban
<a href="http://ketoanthucte.top/thong-tu-133-2016-btc-a2149.html">hoc ke toan tai tu liem</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thanh-xuan-i1160.html">thong tu 133/2016</a> ban
<a href="http://ketoanthucte.top/bai-tap-excel-a2150.html">bai tap excel nang cao</a> ban
<a href="http://ketoanthucte.top/xu-phat-ke-toan-a2148.html">xu phat ke toan</a> ban
<a href="http://ketoanthucte.top/bai-tap-dinh-khoan-ke-toan-a2147.html">bai tap dinh khoan ke toan</a> ban
<a href="http://ketoanthucte.top/phan-mem-ke-toan-a2135.html">phan mem ke toan</a> ban
<a href="http://ketoanthucte.top/thong-tu-ke-toan-a2134.html">thong tu ke toan moi nhat</a> ban
<a href="http://ketoanthucte.top/ke-toan-cong-no-a2145.html">ke toan cong no</a> ban
<a href="http://ketoanthucte.top/ke-toan-tien-luong-a2146.html">ke toan tien luong</a> ban
<a href="http://ketoanthucte.top/ke-toan-excel-a2143.html">ke toan excel</a> ban
<a href="http://ketoanthucte.top/ke-toan-ban-hang-a2142.html">ke toan ban hang</a> ban
<a href="http://ketoanthucte.top/thu-tuc-bhxh-a2139.html">thu tuc bhxh</a> ban
<a href="http://ketoanthucte.top/ke-toan-thue-a2140.html">ke toan thue</a> ban
<a href="http://ketoanthucte.top/khoa-hoc-ke-toan-a21.html">khoa hoc ke toan</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-toan-a23.html">dich vu ke toan</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-khai-thue-hang-thang-i1238.html">kekhaithue</a> ban
<a href="http://ketoanthucte.top/hoc-chung-chi-ke-toan-a24.html">Học chứng chỉ kế toán</a> ban
<a href="http://ketoanthucte.top/dich-vu-ra-soat-don-dep-so-sach-ke-toan-i1240.html">Dịch vụ dọn dẹp sổ sách kế toán </a> ban
<a href="http://ketoanthucte.top/bang-gia-dich-vu-ke-toan-i1262.html">dich vu ke toan tron goi</a> ban
<a href="http://ketoanthucte.top/dao-tao-ke-toan-a11.html">dao tao ke toan</a> ban
<a href="http://ketoanthucte.top/tai-lieu-ke-toan-a12.html">tai lieu ke toan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">xklđ đài loan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-macau-a2116.html">xklđ ma cao</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-dai-loan-a140.html">don hang xkld dai loan</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">don hang xkld macau</a> ban 
<a href="http://anhngunewlight.edu.vn/chi-nhanh-cong-ty-xkld-thang-long-a2117.html">công ty XKLĐ Thăng Long</a> ban

**Comment by craigtaverner** [comment]
The implementations of the nearest-neighbour only search for all objects within an envelope, and do not do any sorting. While it would be possible to change that, it would be a change to the behaviour which would perhaps surprise people, and incur a cost.
