### ISSUE TITLE
TestDynamicLayers fails

### ISSUE THREAD

**Issue by babak4** [neo4j-contrib/spatial#243]
mvn clean install fails, citing:

> getFeatureReader(CQL:Point,class org.opengis.filter.IncludeFilter Filter.INCLUDE)
> Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 44.899 sec <<< FAILURE! - in org.neo4j.gis.spatial.TestDynamicLayers
> testShapefileExport_Map2(org.neo4j.gis.spatial.TestDynamicLayers)  Time elapsed: 0.66 sec  <<< ERROR!
> java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, C:\Users\babak.tourani\neo4j\spatial\target\var\neo4j-db\1
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
> 	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:100)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$194(GraphDatabaseFactory.java:89)
> 	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.reActivateDatabase(Neo4jTestCase.java:160)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:109)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:90)
> 	at junit.framework.TestCase.runBare(TestCase.java:139)
> 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 	at junit.framework.TestResult.run(TestResult.java:125)
> 	at junit.framework.TestCase.run(TestCase.java:129)
> 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
> 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine@4395f52' failed to initialize. Please see attached cause exception.
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
> 	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:508)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> 	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
> 	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:100)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$194(GraphDatabaseFactory.java:89)
> 	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.reActivateDatabase(Neo4jTestCase.java:160)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:109)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:90)
> 	at junit.framework.TestCase.runBare(TestCase.java:139)
> 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 	at junit.framework.TestResult.run(TestResult.java:125)
> 	at junit.framework.TestCase.run(TestCase.java:129)
> 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
> 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> Caused by: java.nio.file.AccessDeniedException: C:\Users\babak.tourani\neo4j\spatial\target\var\neo4j-db\1\schema\label\lucene\labelStore\1\_0.cfs
> 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
> 	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
> 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
> 	at java.nio.file.Files.delete(Files.java:1126)
> 	at org.apache.lucene.store.FSDirectory.deleteFile(FSDirectory.java:217)
> 	at org.apache.lucene.store.NRTCachingDirectory.deleteFile(NRTCachingDirectory.java:118)
> 	at org.neo4j.kernel.api.impl.index.storage.PartitionedIndexStorage.lambda$cleanupLuceneDirectory$0(PartitionedIndexStorage.java:225)
> 	at org.neo4j.io.fs.FileUtils.windowsSafeIOOperation(FileUtils.java:373)
> 	at org.neo4j.kernel.api.impl.index.storage.PartitionedIndexStorage.cleanupLuceneDirectory(PartitionedIndexStorage.java:225)
> 	at org.neo4j.kernel.api.impl.index.storage.PartitionedIndexStorage.cleanupFolder(PartitionedIndexStorage.java:153)
> 	at org.neo4j.kernel.api.impl.index.storage.PartitionedIndexStorage.prepareFolder(PartitionedIndexStorage.java:137)
> 	at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.create(AbstractLuceneIndex.java:85)
> 	at org.neo4j.kernel.api.impl.labelscan.LuceneLabelScanStore.init(LuceneLabelScanStore.java:150)
> 	at org.neo4j.kernel.impl.storageengine.impl.recordstorage.RecordStorageEngine.init(RecordStorageEngine.java:396)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
> 	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:508)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> 	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:99)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
> 	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:100)
> 	at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$194(GraphDatabaseFactory.java:89)
> 	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.reActivateDatabase(Neo4jTestCase.java:160)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:109)
> 	at org.neo4j.gis.spatial.Neo4jTestCase.setUp(Neo4jTestCase.java:90)
> 	at junit.framework.TestCase.runBare(TestCase.java:139)
> 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 	at junit.framework.TestResult.run(TestResult.java:125)
> 	at junit.framework.TestCase.run(TestCase.java:129)
> 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
> 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 

Which results in build failure.

**Comment by craigtaverner** [comment]
The error we see above looks like a filesystem permissions problem:

```
Caused by: java.nio.file.AccessDeniedException: C:\Users\babak.tourani\neo4j\spatial\target\var\neo4j-db\1\schema\label\lucene\labelStore\1_0.cfs
```

Can you check that you really have write access to the path `C:\Users\babak.tourani\neo4j\spatial\target\var\neo4j-db\1\schema\label\lucene\labelStore\`?

**Comment by babak4** [comment]
Yes, It's windows (server 12R2), and I have permissions on all the directories under my user. Just to be on the safe side, I have manually created that folder, and the test still fails... I can try it on a Linux server. Also the build itself succeeds, if I skip tests.

**Comment by babak4** [comment]
I was able to build successfully on Linux (as root user, however).

**Comment by craigtaverner** [comment]
I've no trouble building on Mac and Linux as a normal user. Have not tried windows in a while, but since that test is very old, I'm sure it worked on windows builds too. I strongly suspect there is something specific about the windows environment you are working on. Good luck.

**Comment by danchoi123** [comment]
<a href="http://ketoanthucte.top/viet-email-xin-viec-hay-nhat-i1462.html">viet email xin viec</a> ban
<a href="http://ketoanthucte.top/muc-tieu-nghe-nghiep-trong-cv-xin-viec-i1461.html">muc tieu nghe nghiẹp</a> ban
<a href="http://ketoanthucte.top/tim-viec-lam-them-cho-sinh-vien-i1153.html">viec lam them</a> ban
<a href="http://ketoanthucte.top/thong-tu-95-2016-tt-btc-a2151.html">thong tu 95/2016/btc</a> ban
<a href="http://ketoanthucte.top/thong-tu-133-2016-btc-a2149.html">hoc ke toan tai tu liem</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thanh-xuan-i1160.html">thong tu 133/2016</a> ban
<a href="http://ketoanthucte.top/bai-tap-excel-a2150.html">bai tap excel nang cao</a> ban
<a href="http://ketoanthucte.top/xu-phat-ke-toan-a2148.html">xu phat ke toan</a> ban
<a href="http://ketoanthucte.top/bai-tap-dinh-khoan-ke-toan-a2147.html">bai tap dinh khoan ke toan</a> ban
<a href="http://ketoanthucte.top/phan-mem-ke-toan-a2135.html">phan mem ke toan</a> ban
<a href="http://ketoanthucte.top/thong-tu-ke-toan-a2134.html">thong tu ke toan moi nhat</a> ban
<a href="http://ketoanthucte.top/ke-toan-cong-no-a2145.html">ke toan cong no</a> ban
<a href="http://ketoanthucte.top/ke-toan-tien-luong-a2146.html">ke toan tien luong</a> ban
<a href="http://ketoanthucte.top/ke-toan-excel-a2143.html">ke toan excel</a> ban
<a href="http://ketoanthucte.top/ke-toan-ban-hang-a2142.html">ke toan ban hang</a> ban
<a href="http://ketoanthucte.top/thu-tuc-bhxh-a2139.html">thu tuc bhxh</a> ban
<a href="http://ketoanthucte.top/ke-toan-thue-a2140.html">ke toan thue</a> ban
<a href="http://ketoanthucte.top/khoa-hoc-ke-toan-a21.html">khoa hoc ke toan</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-toan-a23.html">dich vu ke toan</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-khai-thue-hang-thang-i1238.html">kekhaithue</a> ban
<a href="http://ketoanthucte.top/hoc-chung-chi-ke-toan-a24.html">Học chứng chỉ kế toán</a> ban
<a href="http://ketoanthucte.top/dich-vu-ra-soat-don-dep-so-sach-ke-toan-i1240.html">Dịch vụ dọn dẹp sổ sách kế toán </a> ban
<a href="http://ketoanthucte.top/bang-gia-dich-vu-ke-toan-i1262.html">dich vu ke toan tron goi</a> ban
<a href="http://ketoanthucte.top/dao-tao-ke-toan-a11.html">dao tao ke toan</a> ban
<a href="http://ketoanthucte.top/tai-lieu-ke-toan-a12.html">tai lieu ke toan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">xklđ đài loan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-macau-a2116.html">xklđ ma cao</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-dai-loan-a140.html">don hang xkld dai loan</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">don hang xkld macau</a> ban 
<a href="http://anhngunewlight.edu.vn/chi-nhanh-cong-ty-xkld-thang-long-a2117.html">công ty XKLĐ Thăng Long</a> ban
