### ISSUE TITLE
Neo4J 3.0.1 Server Plugin

### ISSUE THREAD

**Issue by lordmj** [neo4j-contrib/spatial#244]
There is a 404 error when trying to download the precompiled version and building the new version of the plugin with maven fails:

"Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project neo4j-spatial: Fatal error compiling: invalid target release: 1.8 -> [Help 1]"

Also before I do this am I able to upgrade my spatial index from neo4j 2.3 to neo4j 3.0.1 ?

**Comment by craigtaverner** [comment]
Neo4j 3.0, and the version of Neo4j Spatial for 3.0, are both built using Java8. The error you are seeing indicates you are trying to build with Java7 or earlier. Make sure you use a Java8 JDK for running maven.

Regarding updating the index, in general is should be compatible, as the index structure has not changed. However there can sometimes be changes to the default key names for some layer types (for example, in 2.3 the WKT layer had the unexpected geometry attribute name 'wkb', which was changed to 'geom' in 3.0). The layer code should have saved the old name and continue using it, but if you do experience problems, this is where they could be, and you could manually fix the attribute names with Cypher as a workaround, or re-import the data to the index.

Note that the current build for 3.0.1 is not final. We are currently making some changes to Neo4j Spatial, and builds for 3.0.2 and later might be more stable.

**Comment by ehx-v1** [comment]
By default Maven sets the JDK to J2SE-1.5, you have to manually change that if you want anything else. I always set the JDK after each pull, because I didn't figure out yet where the related Maven settings are. Anyway, that might have been the problem.

**Comment by ehx-v1** [comment]
And @craigtaverner you mean it's the other way, I remember that issue. It was WKB called wkt

**Comment by danchoi123** [comment]
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-nguyen-chi-thanh-dong-da-i1141.html">hoc ke toan tai nguyen chi thanh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-minh-khai-hai-ba-trung-i1142.html">hoc ke toan tai minh khai</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-long-bien-i1157.html">hoc ke toan tai long bien</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-ha-dong-i1159.html">hoc ke toan tai ha dong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-tu-liem-i1158.html">hoc ke toan tai tu liem</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thanh-xuan-i1160.html">hoc ke toan tai thanh xuan</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-q3-cach-mang-thang-tam-i1162.html">hoc ke toan tai quan 3</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thu-duc-i1161.html">hoc ke toan tai thu duc</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-bien-hoa-i1198.html">hoc ke toan tai dong nai</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-vung-tau-i1263.html">hoc ke toan tai vung tau</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-binh-duong-i1328.html">hoc ke toan tai binh duong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-q-ninh-kieu-can-tho-i1332.html">hoc ke toan tai can tho</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-tp-long-xuyen-an-giang-i1333.html">hoc ke toan tai an giang</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-bac-ninh-i1223.html">hoc ke toan tai bac ninh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-hai-phong-i1222.html">hoc ke toan tai hai phong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-vinh-phuc-i1224.html">hoc ke toan tai vinh phuc</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-quang-ninh-i1225.html">hoc ke toan tai quang ninh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-nam-dinh-i1228.html">hoc ke toan tai nam dinh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-hai-duong-i1229.html">hoc ke toan tai hai duong</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-khai-thue-hang-thang-i1238.html">dich vu ke khai thue</a> ban
<a href="http://ketoanthucte.top/dich-vu-lam-bao-cao-tai-chinh-i1239.html">dich vu lam bctc</a> ban
<a href="http://ketoanthucte.top/dich-vu-ra-soat-don-dep-so-sach-ke-toan-i1240.html">dich vu don dep so sach ke toan</a> ban
<a href="http://ketoanthucte.top/bang-gia-dich-vu-ke-toan-i1262.html">dich vu ke toan tron goi</a> ban
<a href="http://ketoanthucte.top/bai-tap-excel-a2150.html">bai tap excel</a> ban
<a href="http://ketoanthucte.top/thong-tu-133-2016-btc-a2149.html">thong tu 133/2016</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">xklđ đài loan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-macau-a2116.html">xklđ ma cao</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">don hang xkld dai loan</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">don hang xkld macau</a> ban
