### ISSUE TITLE
GeoPipeline: problems upon inheriting

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#245]
I'm inheriting from GeoPipeline. The trouble is that static methods cannot be overridden, so I can't make `start(...)` and `startIntersectWindowSearch(...)` return an instance of my subclass, even though that would be easily possible already in `start(...)`. I would need that for instantiating a custom pipeline properly which has a custom search.
Additionally, for some reason, I can't access any protected members even though I inherit from GeoPipeline. That would be quite useful because I have a workaround that involves shallow-copying a GeoPipeline via subclass constructor. However, not being able to access the protected field `layer` forces me to pass the layer from outside, which makes my workaround quite dirty.
Can you think off anything better? I'd like pretty much to avoid the workaround completely if possible.

**Comment by ehx-v1** [comment]
Update: I noticed that I can access some of the protected members, but by far not all of them. Is it possible that they are private in the JAR? I'm maven-pulling 0.15-neo4j-2.3.0, but look up the code in the master branch, which of course is a far newer version.

**Comment by danchoi123** [comment]
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-nguyen-chi-thanh-dong-da-i1141.html">hoc ke toan tai nguyen chi thanh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-minh-khai-hai-ba-trung-i1142.html">hoc ke toan tai minh khai</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-long-bien-i1157.html">hoc ke toan tai long bien</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-ha-dong-i1159.html">hoc ke toan tai ha dong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-tu-liem-i1158.html">hoc ke toan tai tu liem</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thanh-xuan-i1160.html">hoc ke toan tai thanh xuan</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-q3-cach-mang-thang-tam-i1162.html">hoc ke toan tai quan 3</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thu-duc-i1161.html">hoc ke toan tai thu duc</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-bien-hoa-i1198.html">hoc ke toan tai dong nai</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-vung-tau-i1263.html">hoc ke toan tai vung tau</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-binh-duong-i1328.html">hoc ke toan tai binh duong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-q-ninh-kieu-can-tho-i1332.html">hoc ke toan tai can tho</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-tp-long-xuyen-an-giang-i1333.html">hoc ke toan tai an giang</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-bac-ninh-i1223.html">hoc ke toan tai bac ninh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-hai-phong-i1222.html">hoc ke toan tai hai phong</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-vinh-phuc-i1224.html">hoc ke toan tai vinh phuc</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-quang-ninh-i1225.html">hoc ke toan tai quang ninh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-nam-dinh-i1228.html">hoc ke toan tai nam dinh</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-hai-duong-i1229.html">hoc ke toan tai hai duong</a> ban
<a href="http://ketoanthucte.top/dich-vu-ke-khai-thue-hang-thang-i1238.html">dich vu ke khai thue</a> ban
<a href="http://ketoanthucte.top/dich-vu-lam-bao-cao-tai-chinh-i1239.html">dich vu lam bctc</a> ban
<a href="http://ketoanthucte.top/dich-vu-ra-soat-don-dep-so-sach-ke-toan-i1240.html">dich vu don dep so sach ke toan</a> ban
<a href="http://ketoanthucte.top/bang-gia-dich-vu-ke-toan-i1262.html">dich vu ke toan tron goi</a> ban
<a href="http://ketoanthucte.top/bai-tap-excel-a2150.html">bai tap excel</a> ban
<a href="http://ketoanthucte.top/thong-tu-133-2016-btc-a2149.html">thong tu 133/2016</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">xklđ đài loan</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-macau-a2116.html">xklđ ma cao</a> ban
<a href="http://anhngunewlight.edu.vn/don-hang-xuat-khau-lao-dong-dai-loan-a2115.html">don hang xkld dai loan</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">don hang xkld macau</a> ban

**Comment by ehx-v1** [comment]
Sorry?

Never mind, I decided that for now I'm OK with the workaround.
