### ISSUE TITLE
Plugin for 3.0.1 is now packaged as .jar; README link broken

### ISSUE THREAD

**Issue by funkatron** [neo4j-contrib/spatial#246]
The link under **Using the Neo4j Spatial Server plugin** tries to point to a .zip file, which is not present. The instructions that reference unzipping the plugin file are also invalid for this new version.

Thanks!

**Comment by craigtaverner** [comment]
Thanks for pointing this out. Fixed by https://github.com/neo4j-contrib/spatial/commit/4481b09149cbc684ac3f57d6dbd611a54d189d49
