### ISSUE TITLE
Strange code in SpatialDatabaseService.isValid(Node)

### ISSUE THREAD

**Issue by ehx-v1** [neo4j-contrib/spatial#248]
I've been looking into the SpatialDatabaseService code out of plain interest, and one thing that appeared strange to me is the `isValid(Node)` method. First it marks `null` nodes as invalid, which I could imagine makes sense (although that means it's an overhead ORing the `null` comparision in the `if` of `getSpatialRoot()`). But then it tries to pull a NFE out of `node.getProperty().iterator().hasNext()`, and determines whether the node is valid only based on whether or not the NFE was thrown. I think what the code is supposed to do is check that the node has at least one property. But then it should either return the result of `hasNext()`, or use `next()` instead. As is, it doesn't seem to make any sense at all, especially given that from what I saw no method in the call chain throws a NFE (thus what's there basically means `return true`).

**Comment by craigtaverner** [comment]
The code is curious. I'm not sure under what conditions such a invalid node could occur. The older code just checked for null, but this test was added in 2014 for some reason, presumably due to some specific bad state being reached. The [commit](https://github.com/neo4j-contrib/spatial/commit/2fdc423) does include one extra test, so hopefully any cleanup to the method will fail the test if it does not achieve the same goals. Why not give it a try?

**Comment by ehx-v1** [comment]
What I could imagine after thinking about it, the Spatial root node might have been manually removed from the database, then I assume calling any method to it would result in a NFE. (Then the weird thing about this is that the NFE is not documented, and it's questionable anyway why NFE is uncaught at all, but that's a matter of Neo4j itself.) However, the whole construct implies that it's meant to check for at least one property to exist, which it does not. It should perhaps be reviewed whether the check for at least one property is meant to happen, and if yes the code should be changed so that it actually does this check.

Gesendet von meinem LG Mobile

Am 06.06.2016 18:01 schrieb Craig Taverner <notifications@github.com>:

The code is curious. I'm not sure under what conditions such a invalid node could occur. The older code just checked for null, but this test was added in 2014 for some reason, presumably due to some specific bad state being reached. The commit does include one extra test, so hopefully any cleanup to the method will fail the test if it does not achieve the same goals. Why not give it a try?

**Comment by ehx-v1** [comment]
I issued at Neo4j that NFE should be caught or at least cleanly documented.
As for this point, I couldn't extract the point about this invalid root node from the commit, as both new tests are for the other features of the PR. So @jexp is that code meant to check for at least one property or not?

**Comment by ehx-v1** [comment]
@jexp are you answering questions like this one at all?

**Comment by danchoi123** [comment]
<a href="http://daotaoketoan.top/hoc-ke-toan-tai-le-trong-tan-thanh-xuan-i844.html">học kế toán tại Thanh Xuân</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-cau-giay-i853.html">hoc ke toan tai cau giay</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-long-bien-i848.html">học kế toán tại Long Biên</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-ha-dong-i852.html">học kế toán tại Hà Đông</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-minh-khai-hai-ba-trung-i845.html">hoc ke toan tai minh khai</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-quan-dong-da-i936.html">hoc ke toan tai dong da</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-bac-ninh-i843.html">học kế toán tại Bắc Ninh</a> ban
<a href="http://daotaoketoan.top/trung-tam-dao-tao-ke-toan-tai-quan-thu-duc-i827.html">hoc ke toan tai thu duc</a> ban
<a href="http://daotaoketoan.top/khoa-hoc-ke-toan-tong-hop-thuc-hanh-tai-tphcm-i828.html">hoc ke toan tai tphcm</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-nguyen-chi-thanh-quan-dong-da-i897.html">trung tam ke toan tai dong da</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-minh-khai-hoang-mai-i846.html">lớp học kế toán tại minh khai</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-day-ke-toan-thuc-hanh-tai-cau-giay-i565.html">trung tâm kế toán tại từ liêm</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-ha-dong-i563.html">đào tạo kế toán tại hà đông</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-ke-toan-tai-le-trong-tan-i561.html">học kế toán tại lê trọng tấn</a> ban
<a href="http://trungtamketoanhn.com/trung-tam-dao-tao-ke-toan-tai-long-bien-i564.html">Học kế toán thực tế tại Long Biên</a> ban
<a href="http://trungtamketoanhn.com/khoa-hoc-ke-toan-tong-hop-thuc-hanh-thuc-te-o-bac-ninh-i660.html">trung tâm kế toán bắc ninh</a> ban
<a href="http://trungtamketoanhn.com/khoa-hoc-ke-toan-tong-hop-tai-tphcm-i599.html">trung tâm kế toán tphcm</a> ban
<a href="http://trungtamketoanhn.com/hoc-ke-toan-thuc-hanh-tai-thu-duc-i864.html">học kế toán tại thủ đức</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-thu-duc-i1161.html">lớp học kế toán tại thủ đức</a> ban
<a href="http://ketoanthucte.top/hoc-ke-toan-tai-minh-khai-hai-ba-trung-i1142.html">lớp học kế toán tại minh khai</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-viet-hung-long-bien-i751.html">lớp học kế toán tại long biên</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-quang-trung-ha-dong-i750.html">kế toán hà nội 200 quang trung</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-o-le-trong-tan-i753.html">lớp học kế toán tại thanh xuân</a> ban
<a href="http://hocketoanvn.com/lop-hoc-ke-toan-tong-hop-thuc-hanh-tai-bac-ninh-i709.html">lớp học kế toán tại bắc ninh</a> ban
<a href="http://hocketoanvn.com/lop-hoc-ke-toan-tong-hop-thuc-te-tai-tphcm-i713.html">lớp học kế toán tại q3</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-hai-phong-i734.html">lớp học kế toán tại hải phòng</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-binh-duong-i831.html">lớp học kế toán tại bình dương</a> ban
<a href="http://hocketoanvn.com/hoc-ke-toan-thuc-hanh-tai-hai-duong-i814.html">lớp học kế toán tại hải dương</a> ban
<a href="http://anhngunewlight.edu.vn/xkld-macau-ma-cao-a141.html">xkld macau</a> ban 
<a href="http://anhngunewlight.edu.vn/chi-nhanh-cong-ty-xkld-thang-long-a2117.html">công ty XKLĐ Thăng Long</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-bac-giang-i650.html">Công Ty XKLĐ Bắc Giang</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-hai-duong-i651.html">Công Ty XKLĐ Hải Dương</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-phu-tho-i653.html">Công ty XKLĐ tại Phú Thọ</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-vinh-phuc-i660.html">Công ty XKLĐ tại Vĩnh Phúc</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-thanh-hoa-i661.html">Công ty XKLĐ tại Thanh Hóa</a> ban 
<a href="http://anhngunewlight.edu.vn/cong-ty-xkld-tai-hung-yen-i662.html">Công ty XKLĐ tại Hưng Yên</a> ban

**Comment by craigtaverner** [comment]
It seems likely this code will not change until or unless we re-think the entire concept of the spatial root.
