### ISSUE TITLE
spatial.addNodes using cypher

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/spatial#262]
Hi,

I'm having trouble getting addNodes procedure to work. Basically, I want all of my nodes that hasn't been added yet to the index, to be added to the index.. Below is query I'm using. I'm searching all nodes that has no incoming relationship of type "RTREE_REFERENCE", and then feed those nodes to that procedure.

`match (n:Intersection) WHERE NOT (n)<-[:RTREE_REFERENCE]-() with n  CALL spatial.addNodes("road_network",n) yield node return 1`

Unfortunately, I got this error
`
Type mismatch: expected Collection<Node> but was Node `

Any idea how to properly pass the nodes return from cypher towards the procedure? Thank you!

**Comment by jexp** [comment]
Try

match (n:Intersection) 

WHERE NOT (n)<-[:RTREE_REFERENCE]-() with collect(n) as nodes CALL spatial.addNodes("road_network",nodes) yield node return count(*)

Depending on your volume you might want to batch it


match (n:Intersection) 

WHERE NOT (n)<-[:RTREE_REFERENCE]-() 

With n limit 10000

with collect(n) as nodes CALL spatial.addNodes("road_network",nodes) yield node return count(*)



Von meinem iPhone gesendet

**Comment by vvavepacket** [comment]
Thanks jexp, I see that this do the first 10000, how about the second 10000, the third 10000? Thanks.

**Comment by jexp** [comment]
Those first 10k will then have the relationship so will not be matched again 

Von meinem iPhone gesendet

**Comment by vvavepacket** [comment]
Perfect. Closing the issue as solved. Thankies.
