### ISSUE TITLE
accessing certain columns/properties on spatial procedures

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/spatial#263]
Let's say we are using the spatial.withinDistance procedure. 
`
call spatial.withinDistance("road_network", {lat: 11.11111, lon: 12.222222}, 0.1)`

According to the source code, it returns a NodeDistanceResult which consists of the following

[http://i.imgur.com/Muv4J6y.png](url)

It returns 2 columns of data namely the node and the distance. Now, how do we access only the nodes using cypher? I tried the following but it doesn't work.
`
call spatial.withinDistance("road_network", {lat: 11.11111, lon: 12.222222}, 0.1) yield X.nodes as nodes return nodes`

**Comment by jexp** [comment]
yield node

Or

yield node, distance
