### ISSUE TITLE
FeatureInfo from Geoserver only shows Geometry

### ISSUE THREAD

**Issue by MobiusF** [neo4j-contrib/spatial#266]
When I select a feature in the geoserver preview, I just get a 'fid', not all the properties of the node it's related to.

**Comment by craigtaverner** [comment]
Can you explain the full use case, and in particular how you loaded the data into neo4j so I know what data is there and what should be seen in GeoServer?

**Comment by MobiusF** [comment]
Craig,

Load:
USING PERIODIC COMMIT 1000
LOAD CSV WITH HEADERS FROM 'file:///SELECT_Station_ID_as_ID_Stationsnaam_as_Naam_Nummer_as_Nummer_So_201608311640.csv' as Line FIELDTERMINATOR ';'
CREATE (s:substation {id : Line.ID, name:Line.NAAM, number : Line.NUMMER, kind : Line.SOORT, wkt : Line.LIGGING_MS});

then add to previous created wktlayer
MATCH (s:substation)
WITH collect(s) AS substations
CALL spatial.addNodes('GEOM-WKT',substations) YIELD node
RETURN count(*)

Preview in Geoserver with Openlayers, klik a point-geom:
Request: getFeatureInfo
        PropertyNames = null
        QueryLayers = [org.geoserver.wms.MapLayerInfo@aac36986]
        FeatureCount = 50
        GetMapRequest =
GetMap Request
 version: 1.1.1
 output format: image/png
 width height: 101,101
 bbox: SRSEnvelope[5.526605844497681 : 5.528773069381714, 51.516233682632446 : 51.51840090751648]
 layers: neo4j:GEOM-WKT
 styles: point
        InfoFormat = text/html
        Exceptions = application/vnd.ogc.se_xml
        YPixel = 50
        XPixel = 50
        Version = 1.1.1
        Get = false
        Request = GetFeatureInfo
        BaseUrl = http://localhost:8080/geoserver/
        RawKvp = {FORMAT=image/png, INFO_FORMAT=text/html, STYLES=, WIDTH=101, HEIGHT=101, LAYERS=neo4j:GEOM-WKT, REQUEST=GetFeature
Info, SRS=EPSG:4326, BBOX=5.526605844497681,51.516233682632446,5.528773069381714,51.51840090751648, VERSION=1.1.1, X=50, Y=50, SERVI
CE=WMS, QUERY_LAYERS=neo4j:GEOM-WKT, TRANSPARENT=true, FEATURE_COUNT=50}
        RequestCharset = null

It shows a html table with 1 header and 1 field: fid : 22335

Then in the neo4j browser (kill geoserver and start neo4j !!!! is there any way to use just 1 engine from both geoserver and the neo4j web client??)
MATCH (n:substation) where id(n) = 22335 RETURN n
N looks like:
 substation
<id>: 22335
wkt: POINT (5.52770573420874 51.5173273807227)
number: 143.704
gtype: 1
kind: Netstation
bbox: 5.52770573420874,51.5173273807227,5.52770573420874,51.5173273807227
name: Kwadestraat
id: 64.551.702

So the getFeature does work, but I would have expected the html table to also show the attributes (number, kind, name and id).

Is this enough info? Am I doing something wrong?

BR, M.

**Comment by craigtaverner** [comment]
I've reviewed the code and I think I see the problem. The fact is that neo4j is a schemaless database, which means there is no requirement that each geometry node have the same properties. As a result we need to store the expected list of properties in a separate place. Some of the test code and some of the importer code actually does this for you, but not, it seems, the current procedures.

I have a workaround for you I think will work, as well as a fix I can publish once neo4j 3.0.5 is out (because I've got other fixes relying on 3.0.5).

Workaround:

- get the layer node (was returned by the procedure that added the layer, but you can also use `CALL spatial.layer(name)`.
- set the property `layerprops` on that node to the array of extra attributes you want to see:

```
CALL spatial.layer('GEOM-WKT') YIELD node as layer
SET layer.layerprops = ['name', 'number', 'kind']
RETURN layer
```

Fix:

- I am thinking of adding procedures for `spatial.setFeatureAttributes('mylayer',['a','b','c'])` and `spatial.getFeatureAttributes('mylayer')`, which you can use for setting and getting these attributes.

**Comment by MobiusF** [comment]
Craig,

This does the trick. Great. 

However, this does restrict a layer to 1 type of node. 
I was planning to add geoms of the relations between these nodes to the same layer, guessing it would be better in case I want to add geom-tracing to a client.

As far as I can see, Simple Features are schema agnostic too. Wouldn't it be better to make this transparent. E.g. A Feature Request finds the geom, the attached node is retrieved and all existing properties (except bbox, and in this case the wkt) are returned in the Feature Request response??

BR,

M.

**Comment by craigtaverner** [comment]
I've made a 0.23-neo4j-3.0.4 release with just this fix.

The problem with your idea is that I understand the DataStore interface defines getSchema() and getFeatureReader() as two methods, with the idea being that you call getScheme to get a list of attribute columns, then call getFeatureReader which returns a reader you can iterate over features with, and for each feature (row) extract the attributes based on the list returned by getSchema back in the beginning.

I've checked the code and the existence of the property is checked for each node returned, so if you include all possible attribute names for all nodes in the schema, then you should be able to see all records. Those missing the fields should have empty fields.

**Comment by MobiusF** [comment]
Craig,

Works fine. Also deleteing the list  ( call spatial setFeatureAttributes('mylayer',[] )  

For the suggestion: I didn't look into the code, so I had no idea of getSchema use.
So I will put all node types in separate layers and figure tracing out in a later stage.

Thanks,

BR
