### ISSUE TITLE
How to retrieve the nodes of a layer

### ISSUE THREAD

**Issue by estef1** [neo4j-contrib/spatial#269]
Hello

I have run the following two procedures to load a set of cities as nodes into an existing graph db. How can I retrieve (match) these nodes from the graphdb? It doesn't seem for these nodes to have a label or property describing the layer name ('cities').

CALL spatial.addPointLayer('cities');

CALL spatial.importShapefileToLayer('cities', 'C:/data/Cities.shp')

Thank you

**Comment by estef1** [comment]
the node 'cities' (layer) does not seem to point to the new nodes either.

**Comment by craigtaverner** [comment]
This library was written back in Neo4j 1.x days before there were any node labels. Adding geometries to a layer will create those nodes in the database, but with no layers. Instead there will be a tree structure built into the graph. This tree will have the shape of an RTree spatial index and can be used to find the nodes using methods like spatial.withinDistance. You could also find them using Cypher by looking for patterns like ()-[:RTREE_REFERENCE]->(data). Or you could traverse from the layer node down the rtree graph itself.
