### ISSUE TITLE
Finding the closest point

### ISSUE THREAD

**Issue by Fuv** [neo4j-contrib/spatial#270]
I created a simple point layer and added my points to the index. The question is how to find the closest node that exists in R-Tree? I was using findClosestGeometries, but it seems to find ALL objects that are within the range I specify in the "distanceInKm" parameter and (I guess) because of that this method is rather slow. Is there any other option to do this? And what does setting this parameter to 0 change?

**Comment by craigtaverner** [comment]
I believe this was fixed in 0.25.7. Could you check that or a more recent release, and if it was not your bug fixed, please re/open this with more information.
