### ISSUE TITLE
Cleanup spatial procedures and release library for 3.0

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/spatial#277]
Michael did a great job creating an initial procedures list for 3.0. This card is to review, update and extend that list with the goal of releasing a first version of the Spatial library for Neo4j 3.0.

See https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java

* [x] Review procedures and normalize names
* [x] Add list layers
* [x] Cleanup addLayer with supported named layer types
* [x] Add removeLayer
* [x] Smoke testing
* [x] Publish first draft plugin (0.16)
* [x] Review LayerNodeIndex and verify that Procedures covers all use cases
* [x] Review REST API and verify that Procedures covers all use cases
* [x] Benchmark addNode() versus addNodes()
* [x] Deprecate/Delete IndexProvider (0.17)
* [ ] Documentation
* [ ] Deprecate REST API (0.18)
* [ ] Publish plugin and update README (and email list)
* [ ] Add support for either envelope(geometry) or enrich(geometry) (see LayerNodeIndex analysis below)
* [ ] Add support for addCQLDynamicLayer

**Comment by craigtaverner** [comment]
I think most of this was done, and several releases made since then, including 3.4 and 3.5 with the new native point type. There are loose ends not covered, but I think they should be driven by a new look at the overall requirements.
