### ISSUE TITLE
How to combine neo4j-spatial with mapbox.js.

### ISSUE THREAD

**Issue by cara-shi** [neo4j-contrib/spatial#282]
I want to show the node and the relationship with geospatial location. How to combine neo4j-spatial with mapbox.js. The result is some like https://neo4j.com/blog/new-approach-visualizing-spatial-data/. Thanks!

**Comment by HADDADENICAR** [comment]
me too i want to know

**Comment by craigtaverner** [comment]
I've seen a few blogs by Will Lyon that works with Neo4j Spatial and mapbox. Take a look at:

* https://neo4j.com/blog/geospatial-indexing-us-congress-neo4j/
* https://www.lyonwj.com/2017/11/28/geocoding-paradise-papers-neo4j-spatial-visualization/
* https://medium.com/neo4j/working-with-neo4j-date-and-spatial-types-in-a-react-js-app-5475b5042b50

This last one is based on the new spatial features built into neo4j itself. I'd recommend reading the above blogs and using the ideas there to build a mapbox based GUI.
