### ISSUE TITLE
Failed to invoke procedure `spatial.addPointLayerWithConfig`: Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by m007** [neo4j-contrib/spatial#290]
I'm currently running the official `Neo4j 3.0.4` from duckerhub.com as base for a docker image where I later add `neo4j-spatial-0.23-neo4j-3.0.4-server-plugin.jar` to the plugins directory.

Executing

    CALL spatial.addPointLayerWithConfig('geom', 'longitude:latitude');

results in

    Failed to invoke procedure `spatial.addPointLayerWithConfig`: Caused by: java.lang.NoClassDefFoundError: org/geotools/filter/text/cql2/CQLException

Can anybody reproduce this, offer a solution or is this a real issue?

-----
*Edit*

I found that happens only *after* I importet an *.osm file into the database. It seems, importing the .osm file creates a spatial layer with the name of the importet .osm file. Isn't it possible to create two different spatial layers?

**Comment by craigtaverner** [comment]
Sounds like a bug and a limitation:
bug - incorrect error on adding a layer with existing name
limitation - OSMImporter.main() console app does not allow specifying layer name

In the procedures we supported importing to new layer names for SHP files, but have not done the same for OSM data. We could add `spatial.importOSMToLayer` procedures to provide the functionality you are after.

**Comment by craigtaverner** [comment]
For reference, I added an initial implementation for importing OSM from procedures. It is not well tested, but you could review it at https://github.com/neo4j-contrib/spatial/commit/9e9d5cdcc5dd8b699d9515dc3aaa9f3d6590e690

**Comment by m007** [comment]
> We could add spatial.importOSMToLayer procedures to provide the functionality you are after.

That would be very nice, I'll have a look at 9e9d5cd on monday. 

Regarding importing an .osm file to a layer, I do have another question, which I think is related: Importing an .osm file not just once, but more times (you may have an updated version of this .osm file sometime later). Is there a way to update an existing graph? Or do we have to purge the old one and import the new one?

**Comment by craigtaverner** [comment]
Back when we originally wrote the OSMImporter in 2011, we did start working on graph merge, but did not get that far with it, so I think it does not work at all at the moment. It is a non-trivial problem to solve, but is possible (with some work).

**Comment by m007** [comment]
> [...] so I think it does not work at all at the moment. It is a non-trivial problem to solve, but is possible (with some work).

Updating an existing OSM graph would be a must-have feature in my use case, so I'd very much like to contribute regarding graph merge. Since that is an entirely new issue/feature and this one seems fixed now, I'll open a new issue for graph merge and close this one.
