### ISSUE TITLE
separate the bbox updating from the geometry encoding

### ISSUE THREAD

**Issue by taseroth** [neo4j-contrib/spatial#297]
Currently, adding a node to an layer does lead to adding an 'bbox' attribute AND updating the attribute holding the geometry.

In my case, I use the property that holds the geometry (WKT Point) as an unique index. The re-encoding of the property messes the unique index.

see: https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/DefaultLayer.java#L86

**Comment by craigtaverner** [comment]
I've made a fix for this and pushed it to master. Is that usable, or would you need a new release?

See https://github.com/neo4j-contrib/spatial/commit/df24003dca33038d7ba1a70ad8c0b0b05c7419ea
