### ISSUE TITLE
Export OSMLayer to OSM xml file

### ISSUE THREAD

**Issue by m007** [neo4j-contrib/spatial#299]
It is apparently easy to import an existing `.osm` file into an OSMLayer, but I did not see examples or passges in the code that look like an exporting features for `.osm` files exists.

Is it possible to export an OSMLayer into an OSM xml file? If not, how would one go for supporting that?

**Comment by craigtaverner** [comment]
Exporting to OSM would require writing an exporter from scratch. The in-graph model would need to be converted to the tabular model that is .osm. It is easier probably than importing, but still non-trivial. And the final OSM will not be identical to the original one imported.
