### ISSUE TITLE
Example wrong

### ISSUE THREAD

**Issue by iwillig** [neo4j-contrib/spatial#3]
This a very small issue, but in your first example you show the shapefile importer with the shapefile's path and extension. However, in the code http://github.com/neo4j/neo4j-spatial/blob/master/src/main/java/org/neo4j/gis/spatial/ShapefileImporter.java#L118 the shapefile import appends the path with a file extension.

This is not a biggie, but could cause pain to new users.

**Comment by ehx-v1** [comment]
Actually it would have been a fun-looking alternative to have each shapefile pack for the tests twice, once normally and once with a nested ending, like .shp.shp, .shp.qix and others ;-)

**Comment by ehx-v1** [comment]
Hm, why was my comment added BEFORE the "Closed" icon even though I actually commented afterwards? GitHub normally doesn't do that... Interesting Git bug!
