### ISSUE TITLE
Procedure to remove a node from spatial layer

### ISSUE THREAD

**Issue by tavolate** [neo4j-contrib/spatial#301]
I think will be appreciated a procedure to remove a node from a spatial layer without removing it from the database

**Comment by craigtaverner** [comment]
This has been discussed also at https://github.com/neo4j-contrib/spatial/issues/139. Perhaps we should merge these two issues.

**Comment by craigtaverner** [comment]
I just pushed two small releases that include the ability to remove nodes from layers. See 0.26.2 in https://github.com/neo4j-contrib/spatial/releases
