### ISSUE TITLE
Issue with <relation> elements referring to <way> elements when importing an OSM file

### ISSUE THREAD

**Issue by m007** [neo4j-contrib/spatial#304]
When importing an OSM file via procedure, I get the following logs:

    /var/lib/osm-files/indoor.osm[354]: Cannot find member: {ref=-58, role=shell, type=way}
    /var/lib/osm-files/indoor.osm[364]: Cannot find member: {ref=-52, role=level, type=way}
    /var/lib/osm-files/indoor.osm[380]: Cannot find member: {ref=-54, role=level, type=way}
    ...
    neo4j_1    | /var/lib/osm-files/indoor.osm[495]: When processing the relations, there were 12 missing members
    ...
    Loaded 23 nodes
    Loaded 10 ways
    Loaded 10 relations

So, for an OSM XML `relation` element like:

    <relation changeset="1491466790543" id="-68" timestamp="2017-04-06T08:19:50Z" uid="109761491" user="steve" visible="true">
        <tag k="type" v="building/>
        <member ref="-48" role="shell" type="way"/>
    </relation>

there will no `:MEMBER` relationship created in the graph, since upon creating the graph node for the `<relation>` element the graph node for the `<way>` element is not already created.

I think this seems to be a bug, because it should be possible to use Ways as Members in OSM Relations and they should be imported correct here. Am I wrong?

**Comment by m007** [comment]
@craigtaverner any ideas?

**Comment by craigtaverner** [comment]
That error normally occurs when the OSM file was created by slicing a piece of the bigger OSM graph. When I worked on this a few years back the OSM exporter did not create self-consistent OSM files at all, and they were full of ways that referenced nodes that were not in the file (and relations that reference ways or nodes not in the file).

Can you verify that the referenced member really is in the same OSM file?

Also, I noticed that the ref tags are negative numbers. In the examples I have they are all positive integers. For example:

    <relation id="36165" user="spull" uid="61533" visible="true" version="13" changeset="4892788" timestamp="2010-06-03T13:58:00Z">
      <member type="way" ref="27076093" role=""/>
      <member type="way" ref="51892828" role=""/>
      <member type="way" ref="51892830" role=""/>
      ....
      <tag k="name" v="Söderåsbanan"/>
      <tag k="route" v="railway"/>
      <tag k="type" v="route"/>
     </relation>

**Comment by m007** [comment]
> That error normally occurs when the OSM file was created by slicing a piece of the bigger OSM graph. When I worked on this a few years back the OSM exporter did not create self-consistent OSM files at all, and they were full of ways that referenced nodes that were not in the file (and relations that reference ways or nodes not in the file).

Yeah, I read that in the comments in code of the importer class :v:

Heres the file I used for the import: [full-complex.txt](https://github.com/neo4j-contrib/spatial/files/905901/full-complex.txt)

As you can see, all the `way`s referenced in the `relation`s exist. The negative `id`s do not seem to matter, the problem remains if I change them to positive Integers, too.

**Comment by craigtaverner** [comment]
Perhaps our OSM importer code does not allow negative ids. I'd have to check, but I know all earlier datasets we developed with had only positive numbers.

**Comment by m007** [comment]
I may be wrong and made errors during my tests, but I don't think that is an issue with (negative) Id's. This assumption is based on two reasons:

1. I converted all Id's into positive ones and still had the problem.
2. Negative Id's do **not** prevent `:MEMBER` relationships being created between two `<relation ...`s or a `<relation ...` and a `<node ...` 

I attached two pictures showing those relationships:
![osm-levelconnection](https://cloud.githubusercontent.com/assets/1150332/24897161/24e284c0-1e98-11e7-8614-ee05b7d7d8b2.png)
![osm-relation](https://cloud.githubusercontent.com/assets/1150332/24897160/24d7cc56-1e98-11e7-9217-efe36d48b042.png)

Could you reproduce the behavior with the above given .osm file (full-complex.txt)? I don't mind if you want to use that file for personal testing purposes!

**Comment by brianruf** [comment]
It is not clear if there was ever a resolution of the issue outlined here nearly 5 years ago as I am also having issues with <relation> elements referring to <way> elements when importing an OSM file although in my case it is not associated with negative ID's.    

While MEMBER relations are created for some Relations (routes, restrictions, etc.) they do not seem to be created for multipolygon type relations (see example OSM data below) so I am wondering how to determine with accuracy for example if a point is in a multipolygon (i.e. city) using the corresponding graph model if we can not reconstruct the polygon?

Sample Multipolygon OSM object (parking lot):

<relation id="12093569" visible="true" version="1" changeset="96434220" timestamp="2020-12-25T20:33:07Z" user="AKLAB" uid="2518150">
  <member type="way" ref="888479082" role="outer"/>
  <member type="way" ref="888479083" role="inner"/>
  <tag k="access" v="customers"/>
  <tag k="amenity" v="parking"/>
  <tag k="parking" v="surface"/>
  <tag k="surface" v="asphalt"/>
  <tag k="type" v="multipolygon"/>
 </relation>

![Screenshot 2022-09-07 032427](https://user-images.githubusercontent.com/57507686/188829079-3b33bfb4-1b80-42b8-964d-b24137b8e35f.jpg)

![image](https://user-images.githubusercontent.com/57507686/188829473-9783ef00-14c8-4f22-9bd2-3849f8a45578.png)

As with the original post on this issue, the log reveals a number of (total of 9)  "Cannot find member" messages but these seem to be explainable by the comment from @craigtaverner regarding being caused "by slicing a piece of the bigger OSM graph." which was the case here.

Sample Log Entry for missing members (total of 9 entries):
.\import\KS_JO_135th.osm[447104]: Cannot find member: {type=way, ref=34142211, role=outer}

Also like in the original post, the log also references a total number of missing members which is much larger than the members listed above.  

Log entry for total missing members:   
.\import\KS_JO_135th.osm[471176]: When processing the relations, there were 7294 missing members

Not sure if this log entry may indicate a problem or if the member relations are intestinally not included in this model.  

In any event I would like to be able to accurately determine if points are within OSM multipolygons (not using approximations based on bounding box) and not sure how to do this with this data model.

I have tried this with a large OSM file consisting of a USA county and a much smaller one (i.e. 12K) as outlined here with the same results. 

I am using DBMS Version 4.4.3 on NEO4j Desktop.
