### ISSUE TITLE
geoserver and neo4j server online at the same time

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/spatial#305]
Hi,

Is it possible for neo4j to run in the background, while geoserver is accessding the neo4j database? My goal is neo4j is being updated and would like to reflect the changes on the geoserver map.

It seems when geoserver uses the neo4j database, neo4j server can't access it.. is there any workaround this? i thought neo4j plugin here exposes the calls as REST to geoserver instead of directly taking ownership of database folder. Please help. Thank you.

**Comment by craigtaverner** [comment]
I can think of three options here, of the top of my head:

* Use HA clustering to have the embedded Neo4j running inside GeoServer to sync contents with another Neo4j server instance. This would require the enterprise addition of Neo4j (which implies AGPL).
* Older versions of Neo4j had an unsupported way of launching the server inside embedded mode. See http://fooo.fr/~vjeux/github/github-recommandation/db/doc/manual/html/server-embedded.html#_starting_the_server_from_java. This might be possible with some additional code in newer versions, but would still be unsupported.
* Write a new GeoServer plugin that uses the new Java driver to access a remote Neo4j instance.

This last option is certainly the best option, compatible with the current direction Neo4j is moving in, but might also be quite a bit of work.

**Comment by vvavepacket** [comment]
thanks craig, ill go with the 3rd option. closing this issue.
