### ISSUE TITLE
Problems running neo4j-spatial-0.24-neo4j-3.1.1 on neo4j 3.2.0

### ISSUE THREAD

**Issue by rugsor** [neo4j-contrib/spatial#309]
Hello

Is the spatial plugin 3.1.1 supposed to support latest release of neo4?

When trying to add new nodes to a pointlayer I get a strange error messages indicating that it cant find a node in the RTREE. This error messages references the node by id, and a CYPHER trying to fetch that node by id later runs ok.

If the 3.1.1 plugin on 3.2 db is a bad idea and unsupported I can close this issue. If not - I'm happy to provide more details.

Regards

Rune Sørensen

**Comment by joshuacano** [comment]
+1

**Comment by craigtaverner** [comment]
I'm catching up on older messages. I can say that Neo4j Spatial uses some internal API's and usually will not work on a version of Neo4j for which it was not built. So a build for Neo4j 3.1.x will not work on Neo4j 3.2, as you suspected. I will close this issue, and hope you have tried a newer version of the library with newer versions of Neo4j.
