### ISSUE TITLE
Neo.ClientError.Statement.SyntaxError Unknown procedure output: `node`

### ISSUE THREAD

**Issue by NathHorrigan** [neo4j-contrib/spatial#310]
I'm following multiple tutorials and all demonstrate the same cypher query so it must be correct but I'm getting following error: 
```
Neo.ClientError.Statement.SyntaxError Unknown procedure output: `node`
```

Code:
```
call spatial.addWKTLayer('geom', 'wkt')
------- THEN --------
MATCH (v:Venue) WITH collect(v) as venues
CALL spatial.addNodes('geom', venues) 
YIELD node
RETURN count(*)
```
HELP ME PLEASE!!

**Comment by jexp** [comment]
How / where did you call it?

According to the procedure docs and implementation, `yield node`  is correct.

**Comment by craigtaverner** [comment]
Looking at the code I notice that the addNodes procedure changes signature last November to return a count of nodes added, instead of a stream of nodes added. This was, I believe, in support of using the bulk-load feature for adding nodes much faster, and therefor also supporting much larger numbers of nodes. Since you are passing in the nodes, there is also no real value in getting the node returned.

What should work now would be:

```
call spatial.addWKTLayer('geom', 'wkt')
------- THEN --------
MATCH (v:Venue) WITH collect(v) as venues
CALL spatial.addNodes('geom', venues) 
YIELD count
RETURN count
```

If you really want to yield the node, add one at a time with:

```
call spatial.addWKTLayer('geom', 'wkt')
------- THEN --------
MATCH (v:Venue)
CALL spatial.addNode('geom', v) 
YIELD node
RETURN count(*)
```

**Comment by NathHorrigan** [comment]
@craigtaverner Thanks for the help, but now I'm getting following error:

 > Failed to invoke procedure `spatial.addNodes`: Caused by: org.neo4j.graphdb.NotFoundException: No such property, 'wkt'.

**Comment by qualebs** [comment]
Hi @craigtaverner must the the call to spatial.addWKTLayer('gem', 'wkt') be called for each node or do we call this only for the first node. I am imagining a layer is like a sheet of paper like a Cartesian plane where we add xs and ys. Really a green horn in this. please help

**Comment by craigtaverner** [comment]
Yes, @qualebs, the layer is a kind of collection of similar objects. You should create it once, and then add nodes to it without needing to create it again. When you create a layer we actually save a special layer node in the graph, so any future methods that interact with that layer by name will be able to find it. The reason for having a layer concept is that you could have different layers with different configurations. For example, some might use WKT for storing geometries, while others might be Point layers with latitude and longitude parameters. Only nodes with the correct format for that layer should be added to it.
