### ISSUE TITLE
Run spatial.closest on empty index

### ISSUE THREAD

**Issue by janwo** [neo4j-contrib/spatial#315]
When I run...
    
    call spatial.addPointLayerXY('User', 'test1', 'test2')

...and then search for a pointlayer...

    CALL spatial.closest("User", {latitude: 0, longitude: 0}, 30) YIELD node

... I get an NullPointerException:

    Failed to invoke procedure `spatial.closest`: Caused by: java.lang.NullPointerException

I would expect that I would get an empty result, can somebody check this?

**Comment by craigtaverner** [comment]
Looks like a real bug. I have a fix at https://github.com/neo4j-contrib/spatial/commit/0e1e2e937e46a720c300a00622fb83f7074d972a

This could come out in a new release, but in the meantime, you could try recompile with this fix and see that it works for you.

**Comment by janwo** [comment]
Great, I cannot test this now, but thank you for the fix :)

**Comment by craigtaverner** [comment]
Released 0.24.1 versions with a fix for this and another bug. See https://github.com/neo4j-contrib/spatial/releases/tag/0.24.1-neo4j-3.1.1
