### ISSUE TITLE
Neo4j V3.3.0 compatabiliy

### ISSUE THREAD

**Issue by pazinio** [neo4j-contrib/spatial#323]
Hi,
Any plans to add this great spatial plugin support for latest release - 3.3.0?

Currently it seems broken with several exceptions. :(

Thanks

**Comment by pazinio** [comment]
???

**Comment by craigtaverner** [comment]
I took a look at this today, but a trivial port was not possible. Neo4j 3.3 refactored the internal Cypher types, and this will require a little more work to get Neo4j Spatial to work correctly. I'll try to find the time to do that soon.

**Comment by craigtaverner** [comment]
I got it compiled and tests working, so I've made a release at https://github.com/neo4j-contrib/spatial/releases/tag/0.25-neo4j-3.3.0.

Try it out and let me know if it works OK for you.

**Comment by pazinio** [comment]
Thanks! I will let you know.
