### ISSUE TITLE
Building neo4j-spatial error

### ISSUE THREAD

**Issue by lucapaganotti** [neo4j-contrib/spatial#327]
Hi all, I'm absolutely new to neo4j, I've succesfully installed neo4j server on my debian stretch box, I'm able to run simple queries following the cypher tutorial. Now I would like to add spatial extensions to my server but the build fails this way:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[55,33] cannot find symbol
  symbol:   class CRSTable
  location: package org.neo4j.values.storable
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[56,33] cannot find symbol
  symbol:   class PointValue
  location: package org.neo4j.values.storable
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[718,111] cannot find symbol
  symbol:   class CoordinateReferenceSystem
  location: package org.neo4j.values.storable
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.326 s
[INFO] Finished at: 2018-02-02T10:19:18+01:00
[INFO] Final Memory: 50M/337M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project neo4j-spatial: Compilation failure: Compilation failure:
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[55,33] cannot find symbol
[ERROR] symbol:   class CRSTable
[ERROR] location: package org.neo4j.values.storable
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[56,33] cannot find symbol
[ERROR] symbol:   class PointValue
[ERROR] location: package org.neo4j.values.storable
[ERROR] /home/buck/dev/java/spatial/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java:[718,111] cannot find symbol
[ERROR] symbol:   class CoordinateReferenceSystem
[ERROR] location: package org.neo4j.values.storable
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

so it seems that CRSTable class is missing or much likely I'm missing something.
I followed the instructions you give on these github pages, so I cloned the repository and then run 'mvn install', but it's failing this way.

Thanks by now for any answer and/or driving information.

**Comment by craigtaverner** [comment]
It looks like you might be building the master branch, which is based on neo4j 3.4, which is not released yet. I advise you either download a pre-packaged build for the version you want (see the releases link on the github page), or if you want to build it yourself, make sure you use the correct branch. I'd suggest a branch like 0.25-neo4j-3.3 for use with Neo4j 3.3.

I'll close this issue, but if my advice does not work for you, just re-open it with a comment explaining what you tried and what happened.

**Comment by lucapaganotti** [comment]
Thanks, I had some kind of doubt in cloning the master branch, now I switched to 0.25-neo4j-3.3 one and the building process ends up in the final tests. This is the results output which tells me I have two failures:

Results :

Failed tests: 
  ProgressLoggingListenerTest.testProgressLoggingListnerWithAllLogs:38->testProgressLoggingListenerWithSpecifiedWaits:62 
Argument(s) are different! Wanted:
forwardingPrintStream.println(
    "100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
    "10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)

  ProgressLoggingListenerTest.testProgressLoggingListnerWithOnlyStartAndEnd:46->testProgressLoggingListenerWithSpecifiedWaits:62 
Argument(s) are different! Wanted:
forwardingPrintStream.println(
    "100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
    "10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)


Tests run: 306, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:17 min
[INFO] Finished at: 2018-02-02T14:30:47+01:00
[INFO] Final Memory: 50M/537M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project neo4j-spatial: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/buck/dev/java/spatial/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
