### ISSUE TITLE
Building neo4j spatial error

### ISSUE THREAD

**Issue by lucapaganotti** [neo4j-contrib/spatial#328]
ref. #327 

Thanks, I had some kind of doubt in cloning the master branch, now I switched to 0.25-neo4j-3.3 one and the building process ends up in the final tests. This is the results output which tells me I have two failures:

Results :

Failed tests:
ProgressLoggingListenerTest.testProgressLoggingListnerWithAllLogs:38->testProgressLoggingListenerWithSpecifiedWaits:62
Argument(s) are different! Wanted:
forwardingPrintStream.println(
"100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
"10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)

ProgressLoggingListenerTest.testProgressLoggingListnerWithOnlyStartAndEnd:46->testProgressLoggingListenerWithSpecifiedWaits:62
Argument(s) are different! Wanted:
forwardingPrintStream.println(
"100,00 (10/10) - Completed test"
);
-> at org.neo4j.gis.spatial.ProgressLoggingListenerTest.testProgressLoggingListenerWithSpecifiedWaits(ProgressLoggingListenerTest.java:62)
Actual invocation has different arguments:
forwardingPrintStream.println(
"10.00 (1/10) - Running test"
);
-> at org.neo4j.gis.spatial.rtree.ProgressLoggingListener.lambda$new$0(ProgressLoggingListener.java:46)

Tests run: 306, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:17 min
[INFO] Finished at: 2018-02-02T14:30:47+01:00
[INFO] Final Memory: 50M/537M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project neo4j-spatial: There are test failures.
[ERROR]
[ERROR] Please refer to /home/buck/dev/java/spatial/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by graphadvantage** [comment]
I was able to get the 0.25-neo4j-3.3 branch to build with maven clean install

[INFO] --- maven-install-plugin:2.4:install (default-install) @ neo4j-spatial ---
[INFO] Installing /Users/mooremi8/Documents/spatial/target/neo4j-spatial-0.25.3-neo4j-3.3.1.jar to /Users/mooremi8/.m2/repository/org/neo4j/neo4j-spatial/0.25.3-neo4j-3.3.1/neo4j-spatial-0.25.3-neo4j-3.3.1.jar
[INFO] Installing /Users/mooremi8/Documents/spatial/pom.xml to /Users/mooremi8/.m2/repository/org/neo4j/neo4j-spatial/0.25.3-neo4j-3.3.1/neo4j-spatial-0.25.3-neo4j-3.3.1.pom
[INFO] Installing /Users/mooremi8/Documents/spatial/target/neo4j-spatial-0.25.3-neo4j-3.3.1-server-plugin.jar to /Users/mooremi8/.m2/repository/org/neo4j/neo4j-spatial/0.25.3-neo4j-3.3.1/neo4j-spatial-0.25.3-neo4j-3.3.1-server-plugin.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21:22 min
[INFO] Finished at: 2018-02-06T11:49:05-08:00
[INFO] Final Memory: 75M/713M
[INFO] ------------------------------------------------------------------------
USC02RT819G8WP:spatial mooremi8$

**Comment by craigtaverner** [comment]
@lucapaganotti I got the impression you are passed your problem now, so I can close this issue?

I can also mention that a version for Neo4j 3.4.1 has been published at https://github.com/neo4j-contrib/spatial/releases/tag/0.25.5-neo4j-3.4.1
