### ISSUE TITLE
Predicting Routes Information using Geolocation Trace

### ISSUE THREAD

**Issue by aamalik** [neo4j-contrib/spatial#329]
Hi, 

I am building a backend with neo4j and GTFS(General Transit Feed Specification) data to predict what route a user took using his geolocation(longitude, latitude). With the geolocation trace of a user, I want to find out if he visited a certain known location. These certain known location would be stored in neo4j database.

I am currently considering this Neo4j-spatial plugin and I got confused if this is what I need? 

1. Could this plugin benefit me. And will it be fast enough?
2. Is this exactly the use-case for this plugin?

**Comment by craigtaverner** [comment]
The Neo4j Spatial plugin was originally developed for users of Neo4j as an embedded (library), and supports modeling all kinds of GIS data models, including what you describe above.

However, your description sounds like it does not need something and complex as Neo4j Spatial. You could work just as well with the built-in spatial features in Neo4j itself. There are two options here:

* Neo4j 3.0 (and up to 3.3) support storing locations as latitude and longitude properties on nodes. You could store all your geolocation points as nodes, and have :NEXT relationships between them to define the trace. Then if you are interested in whether a trace passes near a specific point, you could traverse the trace and for each node calculate the distance to your point of interest (using the 'distance' function in Cypher).

* In Neo4j 3.4 released last month the point type is now storable as a property on a node, and can be indexed. This will make the distance function much, much faster, even for much bigger datasets. For example, if you have imported thousands of traces with millions of points, you could still expect millisecond response times for a query like `MATCH (p:Point) WHERE distance(p.location,point_of_interest) < 500 RETURN p`

So if your interest is high performance, I recommend the improved support in Neo4j 3.4.
