### ISSUE TITLE
What version of neo4j-spatial should I install with neo4j v3.2

### ISSUE THREAD

**Issue by renatoargh** [neo4j-contrib/spatial#330]
I am using official Amazon Web Service AMI image for neo4j and the preinstalled version is v3.2.0. What is the best version of neo4j-spatial to use with this specific version?

Which of the following versions is preferable (https://github.com/neo4j-contrib/m2/tree/master/releases/org/neo4j/neo4j-spatial)?
![image](https://user-images.githubusercontent.com/522043/36101139-99dfbbfa-0fef-11e8-8dea-d6468c1f8d5c.png)

**Comment by craigtaverner** [comment]
Between each minor version of Neo4j there can be some API changes that make Neo4j Spatial incompatible. For this reason 0.25-neo4j-3.2.5 is much more likely to work on Neo4j 3.2.0 than the older version for 3.1.4. However, there is a small risk that some unnofficial API's changed between 3.2.0 and 3.2.5 that might affect Neo4j Spatial. I suggest you try this version and see how it goes. If it does not work, you should see very quickly.

If you have troubles, you can open a new issue with the specific case, including error messages, and we can try fix it specifically for 3.2.0.
