### ISSUE TITLE
Not able to import Neo4j Spatial 

### ISSUE THREAD

**Issue by ROJAHEMA** [neo4j-contrib/spatial#334]
I have tried adding SpatialRepository to my project that didnot work then i have cloned this [https://github.com/neo4j-contrib/spatial#examples](url) github project. Still i am unable to add SpatialRepository. I am very new to neo4j please help me to fix this issue.

Stacktrace of my error.

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Neo4j - Spatial Components 0.25.5-neo4j-3.4.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.neo4j:neo4j-spatial-index:jar:3.4.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.636 s
[INFO] Finished at: 2018-05-04T14:47:57+05:30
[INFO] Final Memory: 17M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project neo4j-spatial: Could not resolve dependencies for project org.neo4j:neo4j-spatial:jar:0.25.5-neo4j-3.4.0: Failure to find org.neo4j:neo4j-spatial-index:jar:3.4.0-SNAPSHOT in https://raw.github.com/neo4j-contrib/m2/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of neo4j-contrib-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`
Please help.

**Comment by WuChengbin** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>RADI</groupId>
  <artifactId>neo4j-shapefile</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>neo4j-shapefile</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.9</maven.compiler.source>
	<maven.compiler.target>1.9</maven.compiler.target>
  </properties>
  
  <repositories>
        <repository>
            <id>neo4j-contrib-releases</id>
            <url>https://raw.github.com/neo4j-contrib/m2/master/releases</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>repo2.maven.org</id>
            <name>maven2 repository</name>
            <url>http://repo2.maven.org/maven2/</url>
        </repository>
        <repository>
            <id>osgeo</id>
            <name>Open Source Geospatial Foundation Repository</name>
            <url>http://download.osgeo.org/webdav/geotools/</url>
        </repository>
        <repository>
            <id>neo4j-contrib-snapshots</id>
            <url>https://raw.github.com/neo4j-contrib/m2/master/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-spatial</artifactId>
        <version>0.25.3-neo4j-3.3.1</version>
    </dependency>
        <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j</artifactId>
        <version>3.3.5</version>
    </dependency>
  </dependencies>
</project>

Try this pom.xml，replace the pom.xml in your maven project

**Comment by ROJAHEMA** [comment]
@WuChengbin  Thank you for your response. Its Not working..

`Project build error: Non-parseable POM /home/Java_Workspace/Neo4jSpatial/pom.xml: start tag unexpected character \ua0 (position: START_DOCUMENT seen ...POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n\ua0... @2:2) `

**Comment by WuChengbin** [comment]
@ROJAHEMA Copy denpendencies and repositories tag into pom.xml in your maven project and change the value of properties tag to 1.8 then copy to your pom.xml. Choose build to maven

**Comment by craigtaverner** [comment]
The `master` branch is configured to build against Neo4j 3.4.0 which is not released yet, and it might not be possible to access the SNAPSHOT repositories. If you want 3.4.0 support, it would be better to wait until Neo4j 3.4.0 is released, and then we will update 'Spatial' to depend on the release version.

If instead you are fine with Neo4j 3.3, then check out the 0.25-neo4j-3.3 branch and build that instead.

I am not sure what you mean by 'adding SpatialRepository to my project'. If you mean adding 'Neo4j Spatial' as a maven dependency to another project, then the README has details on how to do that. If you mean something else, please re-open this issue with more details on what you are trying to do.

**Comment by ROJAHEMA** [comment]
@WuChengbin  Not working for above pom.xml

**Comment by ROJAHEMA** [comment]
@craigtaverner  Thank you, I will check with Neo4j 3.3, then check out the 0.25-neo4j-3.3 branch and let you know.

By this 'adding SpatialRepository to my project' i meant, i am unable to extend SpatialRepository or GraphRepository in my interface .

**Comment by ROJAHEMA** [comment]
@craigtaverner  I have used the same versions mentioned by you. Still facing issue in adding neo4j-spatial plugin. Please check


`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Neo4j 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.neo4j:neo4j-spatial:jar:0.25.5-neo4j-3.3.5 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.405 s
[INFO] Finished at: 2018-05-07T18:08:41+05:30
[INFO] Final Memory: 20M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Neo4j: Could not resolve dependencies for project com.neo4j:Neo4j:jar:0.0.1-SNAPSHOT: Failure to find org.neo4j:neo4j-spatial:jar:0.25.5-neo4j-3.3.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
`

**Comment by jagroeneveld** [comment]
Same issue here ;(

**Comment by craigtaverner** [comment]
I see you are actually building for embedded access to the spatial library. In that case you need to add the maven repository where the neo4j-spatial artefacts are published because they are not in maven central. See the instructions in the README at https://github.com/neo4j-contrib/spatial/#using-neo4j-spatial-in-your-java-project-with-maven. The extra piece should look something like:

    <repositories>
        <repository>
            <id>neo4j-contrib-releases</id>
            <url>https://raw.github.com/neo4j-contrib/m2/master/releases</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
