### ISSUE TITLE
surefire test failures building neo4j-spatial

### ISSUE THREAD

**Issue by 100beans** [neo4j-contrib/spatial#337]
Hi,
I am new to Neo4j and get the following error when trying to build the release Spatial 0.25.5-neo4j-3.3.5 using maven.

Tests run: 272, Failures: 1, Errors: 124, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:25 min
[INFO] Finished at: 2018-05-15T15:29:27+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project neo4j-spatial: There are test failures.
[ERROR]
[ERROR] Please refer to C:\spatial\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Best regards,
Ben

**Comment by craigtaverner** [comment]
I am unable to reproduce this. I just checked out branch 0.25-neo4j-3.3 and then did a `mvn clean install`  and all tests pass. If you are able to reproduce this, please re-open the issue with more details about which tests failed and the error messages for the specific failures. The above report only summarizes the fact that one test failed, and gives no details on the failure. That is usually further up in the log.

**Comment by Geoneer** [comment]
Tests run: 301, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46:10 min
[INFO] Finished at: 2019-12-20T00:24:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project neo4j-spatial: There are test failures.
[ERROR]
[ERROR] Please refer to \Neo4J.spatial\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
