### ISSUE TITLE
geohash relationship

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/spatial#341]
Hello i find [here](https://neo4j.com/blog/driving-predictive-analytics-neo4j/#comment-138831) that your plugin have a geohash capability . 
 i need to link my location (lat/lon) nodes with a geohash relationship.
how to do that ?

**Comment by craigtaverner** [comment]
I've reviewed that article and it does not use 'Neo4j Spatial' for geohashing at all. They created their own solution from scratch. Having said that, we did actually support GeoHash based indexes in the 0.25 release (and above) of Neo4j Spatial in November last year (supporting Neo4j 3.0 to 3.3). See the releases at https://github.com/neo4j-contrib/spatial/releases

Geohash only works for points, and so you can only use it for SimplePointLayer. See the examples in the procedure tests at https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L171

Hopefully this answers your questions. I did not understand what you meant by 'geohash relationships', but at least using a geohash based index is now working.

**Comment by HADDADENICAR** [comment]
you said geohash layer is possible with your plugin .
what i want is using geohash ,instead of using R-Tree .
can you answer please [this question](https://stackoverflow.com/questions/50795068/creating-geohash-relationships-in-neo4j)
thanks

**Comment by craigtaverner** [comment]
I've written a new answer on the stackoverflow question.

**Comment by HADDADENICAR** [comment]
i 've seen that you released a new version, is the geohash layer fixed on it ?

**Comment by craigtaverner** [comment]
@HADDADENICAR I'm not sure what you mean. The geohash layer was introduced in 0.25-neo4j-3.0, and has been available since then. When you say 'fixed', you imply there is a bug. Perhaps you could make a bug-report describing the bug and how to reproduce it?
