### ISSUE TITLE
Geohash Level in the geohash Layer

### ISSUE THREAD

**Issue by HADDADENICAR** [neo4j-contrib/spatial#346]
Hello,
as described [in elastic](https://www.elastic.co/guide/en/elasticsearch/guide/current/geohashes.html) there are levels for the geohash from 1-12.
 i can't find a parmater to fix level in : 

     `"spatial.addPointLayerGeohash(name :: STRING?, crsName = wgs84 :: STRING?) :: (node :: NODE?)"`

**Comment by mprins** [comment]
You can just discard tokens from the end of the hash, the concept of levels is native to elastic as is their way of explaining things starting with g for greenland, the actual algorithm is described on wikipedia: https://en.wikipedia.org/wiki/Geohash

**Comment by HADDADENICAR** [comment]
on Wikipedia i find the same thing ! they have mentioned  **GEOHASH LENGTH** which is level in elastic !

**Comment by HADDADENICAR** [comment]
could you just point me to the code where you developed the **Geohash Layer** to see how that works ?

**Comment by craigtaverner** [comment]
@HADDADENICAR This is where the GeoHash is implemented: https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/index/LayerGeohashPointIndex.java#L42

We use the GeoHashUtils from the Lucene library, which converts a single point into a string at the maximum level. We do not use the version of this function that takes a level as an argument. If you think that would be a very useful addition, perhaps you could make a PR with a suggested improvement to the code that provides this capability?
