### ISSUE TITLE
How to improve the speed of spatial query?

### ISSUE THREAD

**Issue by WuChengbin** [neo4j-contrib/spatial#350]
I used 
call spatial.bbox('RainStormEventLayer',{lon:120,lat:30},{lon:130,lat:40}) yield node return node.id
But it took 2 seconds and returned 1000 results.
There are about 49000 nodes in this layer.
Environment:
10c E5 workstation
64g RAM
@craigtaverner

**Comment by WuChengbin** [comment]
I don't quite understand how to use different index for the layer like Hilbert curves, Geohash, and so on
I have increased JVM max Heap to 30g and page cache size to 30g

**Comment by craigtaverner** [comment]
When you create the layer there are various ways of controlling which index is used. See the examples in the test code at :+1: 
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L171
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L181
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L191
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L870
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L878
* https://github.com/neo4j-contrib/spatial/blob/master/src/test/java/org/neo4j/gis/spatial/procedures/SpatialProceduresTest.java#L886

**Comment by WuChengbin** [comment]
Thanks a lot！
Let me have a try
:)

**Comment by WuChengbin** [comment]
One more questions, if I need to add polygon rather than points to Layer, it seems that i just have one choice - RTree?

**Comment by craigtaverner** [comment]
Correct. Today the only index supporting polygons is the RTree. We are thinking of making a layered geohash for polygons, but that is just an idea at the moment.

**Comment by craigtaverner** [comment]
Since I answered the questions, I'm closing this issue. If you have more questions, you can re-open it, or make a new issue.
