### ISSUE TITLE
Do you have A plan to support Neo4j 4.0 ?

### ISSUE THREAD

**Issue by codingmiao** [neo4j-contrib/spatial#367]
Neo4j 4.0 has many nice features, but spatial only supports 2.5.2, Looking forward to integration with it

**Comment by craigtaverner** [comment]
We've started porting some of the related spatial projects to 4.0. Both https://github.com/neo4j-contrib/spatial-algorithms and https://github.com/neo4j-contrib/osm are ported to 4.0, but not yet released (you can now built them for 4.0 yourself).

This project is next in line. All three are maintained on a volunteer basis, so need free time to work on. I'll try get to this one soon. If it is urgent, you are welcome to try port it yourself, looking at the changes we made to the above two projects for inspiration.
