### ISSUE TITLE
RoadMap of neo4j-spatial?

### ISSUE THREAD

**Issue by ventlam** [neo4j-contrib/spatial#53]
I found the http://components.neo4j.org/neo4j-spatial/ page have been remove ,so i can't to reach  the road map of this project.Is there any idea about it?

**Comment by ehx-v1** [comment]
oh wow, that means WKT layers will be auto-indexed too? sounds awesome!

**Comment by craigtaverner** [comment]
I've just stumbled across this old discussion. Things sure worked out differently than planned. We did finally get real spatial support in Neo4j, including automatic indexeing, in the 3.4 release in 2018, but it was for points only. There certainly are plans for more spatial work going forward, but just as was the case with this discussion back in 2014, we really do not know which releases will support which features. Last year I gave a few presentations geared towards showing what 3.4 can do, and what you need to build yourself if you want go beyond that. Please refer to those presentations or the posts on community.neo4j.com for more information on roadmap.
