### ISSUE TITLE
server plugin zip

### ISSUE THREAD

**Issue by bazo** [neo4j-contrib/spatial#54]
in Using the Neo4j Spatial Server plugin section of the readme it says that Neo4j Spatial is also packaged as a ZIP file that can be unzipped into the Neo4j Server /plugin directory.

where can i find this plugin?

**Comment by ehx-v1** [comment]
as I feel like people are still confused about it, i'll give a full explanation of where exactly the ZIP can be got:

1. on top of the GitHub front page, there are 3 head lines: one with the commits branches etc. stuff, the next one is a multi-colored bar which shows how much of which language is in here, and third one starts with the buttons "Branch: master" and "New pull request", the three lines are straight below the description

2. in the third head line on the very right, you will find a button "Download ZIP"

3. that's the ZIP you need

**Comment by pboling** [comment]
Bottom right corner of this image:
<img width="1001" alt="downloadzip" src="https://cloud.githubusercontent.com/assets/19505/15119167/97e16f96-15dd-11e6-9d27-e4c10769b4b1.png">

**Comment by ehx-v1** [comment]
ah sure, a pic is of course more helpful than my text
