### ISSUE TITLE
geoserver plugin installation issue

### ISSUE THREAD

**Issue by mwmitchell** [neo4j-contrib/spatial#56]
I can't get the neo4j-geoserver plugin to work (GeoServer 2.1.4, MacOS) when I follow the instructions on the main page, GeoServer starts up, and in the console are errors (errors pasted below). The only way I got this to work is to copy the neo4j lib contents (from the downloaded distribution) into GeoServer WEB-INF/lib, then copy ONLY the neo4j-spatial-0.9-SNAPSHOT.jar into GeoServer WEB-INF/lib. So maybe this is just a documentation issue?

-- in the geoserver UI console after starting:
- GEOSERVER_DATA_DIR: /Applications/GeoServer.app/Contents/Resources/Java/data_dir
  Loaded style 'burg'
  Loaded style 'capitals'
  Loaded style 'cite_lakes'
  Loaded style 'dem'
  Loaded style 'giant_polygon'
  Loaded style 'grass'
  Loaded style 'green'
  Loaded style 'line'
  Loaded style 'poi'
  Loaded style 'point'
  Loaded style 'poly_landmarks'
  Loaded style 'polygon'
  Loaded style 'pophatch'
  Loaded style 'population'
  Loaded style 'rain'
  Loaded style 'raster'
  Loaded style 'restricted'
  Loaded style 'simple_roads'
  Loaded style 'simple_streams'
  Loaded style 'tiger_roads'
  Loaded default workspace cite
  Loaded workspace 'cite'
  Loaded workspace 'it.geosolutions'
  Loaded workspace 'nurc'
  Loaded workspace 'sde'
  Loaded workspace 'sf'
  Loaded workspace 'tiger'
  Loaded workspace 'topp'
  Loaded store 'arcGridSample', enabled
  Loaded coverage store 'arcGridSample'
  Invocation of destroy method failed on bean with name 'geoServerLoader': java.lang.NullPointerException
  Context initialization failed

When I visit http://localhost:8080/geoserver/web, I get:

HTTP ERROR: 503

SERVICE_UNAVAILABLE
RequestURI=/geoserver/web

**Comment by ehx-v1** [comment]
duplicate to which issue exactly?

**Comment by craigtaverner** [comment]
I think Peter's response answered the question.
