### ISSUE TITLE
Spatial indexes cannot be deleted

### ISSUE THREAD

**Issue by jonathanwin** [neo4j-contrib/spatial#70]
Deleting indexes is done via the Index.delete() method.

This method is unimplemented in LayerNodeIndex.

see https://groups.google.com/forum/#!topic/neo4j/SIxUsF2EExc "neo4j-spatial: Creating a WKT-based index for polygon geometries"

**Comment by craigtaverner** [comment]
The PR above does not fix this issue. I did some work to improve the test and additional debugging, and it seems the index deletion commands are processed in order, and yet the index still remains. It is not clear why. Index deletion is occurring in the same transaction as layer and rtree deletion, but the internal index deletion code does not seem to have a problem with that. Further investigation needed.
