### ISSUE TITLE
neo4j spatial plugin to uDig and geoServer

### ISSUE THREAD

**Issue by mfathi** [neo4j-contrib/spatial#86]
can any one help me how to integrate neo4j with udig and geosever

**Comment by ehx-v1** [comment]
first link more precisely:

- https://github.com/neo4j-contrib/spatial#neo4j-spatial-geoserver-plugin

- https://github.com/neo4j-contrib/spatial#using-neo4j-spatial-with-udig

**Comment by craigtaverner** [comment]
I found mention of both geoserver and udig in the readme. I think that is sufficient.
