### ISSUE TITLE
unable to install the plugin

### ISSUE THREAD

**Issue by scdicks** [neo4j-contrib/spatial#89]
cp neo4j-spatial-0.11-SNAPSHOT-server-plugin.zip ~/neo4j-community-1.8.2/plugins/
cd ~/neo4j-community-1.8.2/plugins/
unzip neo4j-spatial-0.11-SNAPSHOT-server-plugin.zip 
cd ..
ls plugins
[many jars and the zip]
bin/neo4j start
curl http://localhost:7474/db/data/

{
  "extensions" : {
    "CypherPlugin" : {
      "execute_query" : "http://localhost:7474/db/data/ext/CypherPlugin/graphdb/execute_query"
    },
    "GremlinPlugin" : {
      "execute_script" : "http://localhost:7474/db/data/ext/GremlinPlugin/graphdb/execute_script"
    }
  },
  "node" : "http://localhost:7474/db/data/node",
  "reference_node" : "http://localhost:7474/db/data/node/0",
  "node_index" : "http://localhost:7474/db/data/index/node",
  "relationship_index" : "http://localhost:7474/db/data/index/relationship",
  "extensions_info" : "http://localhost:7474/db/data/ext",
  "relationship_types" : "http://localhost:7474/db/data/relationship/types",
  "batch" : "http://localhost:7474/db/data/batch",
  "cypher" : "http://localhost:7474/db/data/cypher",
  "neo4j_version" : "1.8.2"
}

**Comment by ehx-v1** [comment]
I'm not getting it
first comment:
/plugins:
commons-lang-2.4.jar
commons-pool-1.5.4.jar
concurrentlinkedhashmap-lru-1.3.1.jar
geronimo-jta_1.1_spec-1.1.1.jar
gt-api-8.4.jar
gt-coverage-8.4.jar
gt-cql-8.4.jar
gt-data-8.4.jar
gt-main-8.4.jar
gt-metadata-8.4.jar
gt-opengis-8.4.jar
gt-process-8.4.jar
gt-referencing-8.4.jar
gt-render-8.4.jar
gt-shapefile-8.4.jar
imageio-ext-tiff-1.1.5.jar
imageio-ext-utilities-1.1.5.jar
jai_codec-1.1.3.jar
jai_core-1.1.3.jar
jai_imageio-1.1.jar
jdom-1.0.jar
jgridshift-1.0.jar
json-simple-1.1.jar
jsr-275-1.0-beta-2.jar
jt-utils-1.3.0.jar
jt-zonalstats-1.3.0.jar
jts-1.12.jar
lucene-core-3.6.2.jar
neo4j-1.9-20130424.000940-135.jar
neo4j-cypher-1.9-20130424.000816-135.jar
neo4j-graph-algo-1.9-20130424.000641-135.jar
neo4j-graph-collections-0.5.jar
neo4j-graph-matching-1.9-20130424.000656-135.jar
neo4j-jmx-1.9-20130424.000434-135.jar
neo4j-kernel-1.9-20130424.000408-135.jar
neo4j-lucene-index-1.9-20130424.000623-135.jar
**neo4j-spatial-0.11-SNAPSHOT-server-plugin.zip
neo4j-spatial-0.11-SNAPSHOT.jar**
neo4j-udc-1.9-20130424.000456-135.jar
scala-library-2.10.0.jar
vecmath-1.3.2.jar
xercesImpl-2.4.0.jar

the plugin is right at the bold spot! what was the problem?
