### ISSUE TITLE
import shapefiles in Neo4j

### ISSUE THREAD

**Issue by Gaymen** [neo4j-contrib/spatial#96]
how can I import shapefiles in Neo4j ??
I found this code in May ghithub but i ro no wher he set 

GraphDatabaseService database = new EmbeddedGraphDatabase (storeDir);
try {
     ShapefileImporter import = new ShapefileImporter (database);
     importer.importShapefile ("roads.shp", "layer_roads");
Finally {}
     database.shutdown ();
}

Thank you for helping me and give me an example

**Comment by ehx-v1** [comment]
roads.shp is the example shapefile, and `layer_roads` is the layer it's written too, which from what i get should but doesn't need to be named accordingly
however, I've been wondering why the sample code doesn't use a shutdown hook, which would be more simple than `try-finally`?

**Comment by craigtaverner** [comment]
There is a `ShapefileImporter` which can be run on the command-line, or from within Java code, as shown in many test cases, like https://github.com/neo4j-contrib/spatial/blob/8871a1959a998cd34ff2d8e9943c7777ad93a5d9/src/test/java/org/neo4j/gis/spatial/TestSpatial.java#L217.

The new procedures also have support. See `spatial.importShapefile` and `spatial.importShapefileToLayer`.
